-- 井戸端会議: CSV 議論トピックをコミュニティルームとして投入
-- 大カテゴリ 6 + コミュニティルーム 62 + トピック 186

BEGIN;

DELETE FROM public.forum_room_topics WHERE room_id LIKE 'ido-%' OR room_id LIKE 'room-%--community--%';
DELETE FROM public.forum_rooms WHERE id LIKE 'ido-%' OR id LIKE 'room-%--community--%';
UPDATE public.forum_categories SET is_active = false, updated_at = now() WHERE slug LIKE 'ido-%';


INSERT INTO public.forum_categories (slug, name, description, color, sort_order, is_active, tags)
VALUES
  ('ai-technology', 'AI・テクノロジー活用', 'A. AI・テクノロジー活用', '#4A90D9', 0, true, ARRAY['井戸端', 'AI', 'テクノロジー']),
  ('evaluation-curriculum', '評価・学力・カリキュラム', 'B. 評価・学力・カリキュラム', '#E67E22', 1, true, ARRAY['井戸端', '評価', 'カリキュラム']),
  ('children-rights-discipline', '子どもの権利・生活・規律', 'C. 子どもの権利・生活・規律', '#9B59B6', 2, true, ARRAY['井戸端', '子ども', '校則']),
  ('diversity-inclusion', '多様性・包摂・公正', 'D. 多様性・包摂・公正', '#1ABC9C', 3, true, ARRAY['井戸端', '多様性', '包摂']),
  ('teacher-school-system', '教師・学校経営・制度', 'E. 教師・学校経営・制度', '#E74C3C', 4, true, ARRAY['井戸端', '教師', '制度']),
  ('subject-teaching', '教科の指導', 'F. 教科の指導', '#F39C12', 5, true, ARRAY['井戸端', '教科', '学習'])

ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name, description = EXCLUDED.description, color = EXCLUDED.color,
  sort_order = EXCLUDED.sort_order, is_active = EXCLUDED.is_active, tags = EXCLUDED.tags, updated_at = now();

INSERT INTO public.forum_rooms (id, name, description, emoji, weekly_topic, ai_discussion, ai_weekly_topic_enabled, is_hidden, category_id, sub_category_id)
SELECT
  'cat-' || c.slug || '--' || sc.slug,
  c.name || ' / ' || sc.name,
  CASE WHEN sc.slug = 'community' THEN c.name || ' に関する話題を自由に語り合うコミュニティ掲示板です。'
       ELSE c.name || ' に関連する' || sc.name || 'について語り合う部屋です。' END,
  '💬', '', true, false, false, c.id, sc.id
FROM public.forum_categories c
CROSS JOIN public.forum_sub_categories sc
WHERE c.slug IN ('ai-technology','evaluation-curriculum','children-rights-discipline','diversity-inclusion','teacher-school-system','subject-teaching')
  AND sc.is_active = true
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description,
  category_id = EXCLUDED.category_id, sub_category_id = EXCLUDED.sub_category_id, updated_at = now();


-- ユーザー作成コミュニティルームは sub_category_id を NULL（cat-*--community が一意制約を占有）
INSERT INTO public.forum_rooms (id, name, description, emoji, weekly_topic, ai_discussion, ai_weekly_topic_enabled, is_hidden, category_id, sub_category_id)
SELECT v.room_id, v.room_name, v.room_desc, '💬', v.weekly_topic, true, false, false, c.id, NULL::uuid
FROM (VALUES
  ('room-ai-technology--community--gen-ai-education', '生成AIの教育利用', 'A. AI・テクノロジー活用 › 生成AIの教育利用 の議論スペース', '生成AIを児童生徒に何歳から使わせるべきか', 'ai-technology'),
  ('room-ai-technology--community--programming-education', 'プログラミング教育', 'A. AI・テクノロジー活用 › プログラミング教育 の議論スペース', 'プログラミングは全児童生徒に必修とすべきか', 'ai-technology'),
  ('room-ai-technology--community--digital-textbook', 'デジタル教科書', 'A. AI・テクノロジー活用 › デジタル教科書 の議論スペース', '紙の教科書を全面的にデジタルへ移行すべきか', 'ai-technology'),
  ('room-ai-technology--community--giga-one-device', 'GIGAスクール・1人1台端末', 'A. AI・テクノロジー活用 › GIGAスクール・1人1台端末 の議論スペース', 'GIGA端末の家庭への持ち帰りを認めるべきか', 'ai-technology'),
  ('room-ai-technology--community--school-dx', '校務のDX・デジタル化', 'A. AI・テクノロジー活用 › 校務のDX・デジタル化 の議論スペース', '校務支援システムは教員の負担を減らしたか', 'ai-technology'),
  ('room-ai-technology--community--data-driven-education', 'データに基づく教育', 'A. AI・テクノロジー活用 › データに基づく教育 の議論スペース', '学習ログを指導にどこまで活用すべきか', 'ai-technology'),
  ('room-ai-technology--community--edtech-adoption', 'EdTech・教育サービス導入', 'A. AI・テクノロジー活用 › EdTech・教育サービス導入 の議論スペース', '学校はEdTechサービスをどう選定すべきか', 'ai-technology'),
  ('room-ai-technology--community--online-remote-learning', 'オンライン授業・遠隔教育', 'A. AI・テクノロジー活用 › オンライン授業・遠隔教育 の議論スペース', 'オンライン授業は対面授業の代わりになるか', 'ai-technology'),
  ('room-ai-technology--community--ai-literacy-moral', 'AIリテラシー・情報モラル教育', 'A. AI・テクノロジー活用 › AIリテラシー・情報モラル教育 の議論スペース', 'AIリテラシー教育は何歳から始めるべきか', 'ai-technology'),
  ('room-ai-technology--community--personalized-learning', '個別最適化学習', 'A. AI・テクノロジー活用 › 個別最適化学習 の議論スペース', '個別最適化学習は学びを豊かにするか、孤立させるか', 'ai-technology'),
  ('room-evaluation-curriculum--community--national-achievement-test', '学力テスト・全国学力調査', 'B. 評価・学力・カリキュラム › 学力テスト・全国学力調査 の議論スペース', '全国学力調査の結果を学校間で公開すべきか', 'evaluation-curriculum'),
  ('room-evaluation-curriculum--community--grade-evaluation', '成績評価・通知表のあり方', 'B. 評価・学力・カリキュラム › 成績評価・通知表のあり方 の議論スペース', '数値による成績評価は必要か', 'evaluation-curriculum'),
  ('room-evaluation-curriculum--community--entrance-exam-reform', '入試制度改革', 'B. 評価・学力・カリキュラム › 入試制度改革 の議論スペース', '一発勝負の入試は公平か', 'evaluation-curriculum'),
  ('room-evaluation-curriculum--community--inquiry-pbl', '探究学習・PBL', 'B. 評価・学力・カリキュラム › 探究学習・PBL の議論スペース', '探究学習は本当に学力を伸ばすか', 'evaluation-curriculum'),
  ('room-evaluation-curriculum--community--steam-education', 'STEAM教育', 'B. 評価・学力・カリキュラム › STEAM教育 の議論スペース', 'STEAM教育は文系・理系の枠を越えられるか', 'evaluation-curriculum'),
  ('room-evaluation-curriculum--community--reading-literacy', '読解力・言語能力の育成', 'B. 評価・学力・カリキュラム › 読解力・言語能力の育成 の議論スペース', 'デジタル時代に読解力をどう育てるか', 'evaluation-curriculum'),
  ('room-evaluation-curriculum--community--homework', '宿題・家庭学習', 'B. 評価・学力・カリキュラム › 宿題・家庭学習 の議論スペース', '宿題は必要か、あるとすればどうあるべきか', 'evaluation-curriculum'),
  ('room-evaluation-curriculum--community--mastery-based-instruction', '習熟度別指導', 'B. 評価・学力・カリキュラム › 習熟度別指導 の議論スペース', '習熟度別クラス編成は是か非か', 'evaluation-curriculum'),
  ('room-evaluation-curriculum--community--course-of-study-revision', '学習指導要領の改訂', 'B. 評価・学力・カリキュラム › 学習指導要領の改訂 の議論スペース', '学習指導要領は現場の自由度を奪っているか', 'evaluation-curriculum'),
  ('room-evaluation-curriculum--community--non-cognitive-skills', '非認知能力の育成', 'B. 評価・学力・カリキュラム › 非認知能力の育成 の議論スペース', '非認知能力は学校で育てられるか', 'evaluation-curriculum'),
  ('room-children-rights-discipline--community--school-rules-guidance', '校則・生徒指導', 'C. 子どもの権利・生活・規律 › 校則・生徒指導 の議論スペース', '校則をどこまで子ども自身に決めさせるべきか', 'children-rights-discipline'),
  ('room-children-rights-discipline--community--bullying-prevention', 'いじめ対策', 'C. 子どもの権利・生活・規律 › いじめ対策 の議論スペース', 'いじめの「重大事態」をどう線引きするか', 'children-rights-discipline'),
  ('room-children-rights-discipline--community--school-refusal-support', '不登校支援', 'C. 子どもの権利・生活・規律 › 不登校支援 の議論スペース', '不登校の子に学校以外の学びをどこまで認めるか', 'children-rights-discipline'),
  ('room-children-rights-discipline--community--children-rights-voice', '子どもの権利・意見表明', 'C. 子どもの権利・生活・規律 › 子どもの権利・意見表明 の議論スペース', '子どもの声を学校運営にどう反映させるか', 'children-rights-discipline'),
  ('room-children-rights-discipline--community--smartphone-sns', 'スマホ・SNSとの付き合い方', 'C. 子どもの権利・生活・規律 › スマホ・SNSとの付き合い方 の議論スペース', 'スマホの校内持ち込みを認めるべきか', 'children-rights-discipline'),
  ('room-children-rights-discipline--community--uniform-dress-code', '制服・服装の自由', 'C. 子どもの権利・生活・規律 › 制服・服装の自由 の議論スペース', '制服は必要か', 'children-rights-discipline'),
  ('room-children-rights-discipline--community--club-activities', '部活動のあり方', 'C. 子どもの権利・生活・規律 › 部活動のあり方 の議論スペース', '部活動の強制加入は是か非か', 'children-rights-discipline'),
  ('room-children-rights-discipline--community--mental-health', '子どものメンタルヘルス', 'C. 子どもの権利・生活・規律 › 子どものメンタルヘルス の議論スペース', '学校はメンタルヘルスにどこまで踏み込むべきか', 'children-rights-discipline'),
  ('room-children-rights-discipline--community--child-abuse-protection', '児童虐待・要保護児童への対応', 'C. 子どもの権利・生活・規律 › 児童虐待・要保護児童への対応 の議論スペース', '学校はどこまで家庭に介入すべきか', 'children-rights-discipline'),
  ('room-children-rights-discipline--community--corporal-punishment-guidance', '体罰・指導の線引き', 'C. 子どもの権利・生活・規律 › 体罰・指導の線引き の議論スペース', '厳しい指導と体罰の線引きをどこに置くか', 'children-rights-discipline'),
  ('room-diversity-inclusion--community--inclusive-special-needs', 'インクルーシブ教育・特別支援', 'D. 多様性・包摂・公正 › インクルーシブ教育・特別支援 の議論スペース', '障害のある子への合理的配慮をどこまで提供すべきか', 'diversity-inclusion'),
  ('room-diversity-inclusion--community--multicultural-foreign-roots', '外国にルーツのある子どもの教育', 'D. 多様性・包摂・公正 › 外国にルーツのある子どもの教育 の議論スペース', '日本語指導をどう充実させるか', 'diversity-inclusion'),
  ('room-diversity-inclusion--community--gifted-talent-education', 'ギフテッド・才能教育', 'D. 多様性・包摂・公正 › ギフテッド・才能教育 の議論スペース', '特異な才能のある子への支援は必要か', 'diversity-inclusion'),
  ('room-diversity-inclusion--community--educational-poverty-gap', '教育格差・貧困と学習支援', 'D. 多様性・包摂・公正 › 教育格差・貧困と学習支援 の議論スペース', '貧困家庭の子の学習支援を学校はどこまで担うべきか', 'diversity-inclusion'),
  ('room-diversity-inclusion--community--gender-education', 'ジェンダーと教育', 'D. 多様性・包摂・公正 › ジェンダーと教育 の議論スペース', '名簿・呼称・制服のジェンダー配慮をどう進めるか', 'diversity-inclusion'),
  ('room-diversity-inclusion--community--sex-education', '性教育', 'D. 多様性・包摂・公正 › 性教育 の議論スペース', '性教育をどこまで踏み込んで行うべきか', 'diversity-inclusion'),
  ('room-diversity-inclusion--community--multicultural-coexistence', '多文化共生教育', 'D. 多様性・包摂・公正 › 多文化共生教育 の議論スペース', '多文化共生をどう学校文化に根づかせるか', 'diversity-inclusion'),
  ('room-diversity-inclusion--community--night-junior-high', '夜間中学・学び直し', 'D. 多様性・包摂・公正 › 夜間中学・学び直し の議論スペース', '学び直しの機会をどう保障するか', 'diversity-inclusion'),
  ('room-diversity-inclusion--community--medical-care-children', '医療的ケア児への対応', 'D. 多様性・包摂・公正 › 医療的ケア児への対応 の議論スペース', '医療的ケア児の通常学級での学びをどう支えるか', 'diversity-inclusion'),
  ('room-diversity-inclusion--community--diverse-learning-places', '多様な学びの場の保障', 'D. 多様性・包摂・公正 › 多様な学びの場の保障 の議論スペース', 'フリースクールを正式な学びの場と認めるべきか', 'diversity-inclusion'),
  ('room-teacher-school-system--community--teacher-work-style-reform', '教員の働き方改革', 'E. 教師・学校経営・制度 › 教員の働き方改革 の議論スペース', '教員の働き方改革のために何を削るべきか', 'teacher-school-system'),
  ('room-teacher-school-system--community--teacher-shortage-recruitment', '教員不足・採用・人材確保', 'E. 教師・学校経営・制度 › 教員不足・採用・人材確保 の議論スペース', '教員不足をどう解消するか', 'teacher-school-system'),
  ('room-teacher-school-system--community--teacher-licensure', '教員養成・免許制度', 'E. 教師・学校経営・制度 › 教員養成・免許制度 の議論スペース', '教員免許制度は今のままでよいか', 'teacher-school-system'),
  ('room-teacher-school-system--community--teacher-training', '教員研修・専門性開発', 'E. 教師・学校経営・制度 › 教員研修・専門性開発 の議論スペース', '教員研修は教育の質向上に役立っているか', 'teacher-school-system'),
  ('room-teacher-school-system--community--club-community-transition', '部活動の地域移行', 'E. 教師・学校経営・制度 › 部活動の地域移行 の議論スペース', '部活動の地域移行を進めるべきか', 'teacher-school-system'),
  ('room-teacher-school-system--community--school-consolidation', '学校統廃合・小規模校', 'E. 教師・学校経営・制度 › 学校統廃合・小規模校 の議論スペース', '小規模校の統廃合をどう判断すべきか', 'teacher-school-system'),
  ('room-teacher-school-system--community--school-family-community', '学校と家庭・地域の連携', 'E. 教師・学校経営・制度 › 学校と家庭・地域の連携 の議論スペース', '学校・家庭・地域の役割分担をどう設計するか', 'teacher-school-system'),
  ('room-teacher-school-system--community--parent-demands', '保護者対応・学校への要求', 'E. 教師・学校経営・制度 › 保護者対応・学校への要求 の議論スペース', '過剰な保護者要求に学校はどこまで応じるべきか', 'teacher-school-system'),
  ('room-teacher-school-system--community--principal-leadership', '校長・管理職のリーダーシップ', 'E. 教師・学校経営・制度 › 校長・管理職のリーダーシップ の議論スペース', '管理職に求められるリーダーシップとは何か', 'teacher-school-system'),
  ('room-teacher-school-system--community--education-governance', '教育行政・教育委員会のガバナンス', 'E. 教師・学校経営・制度 › 教育行政・教育委員会のガバナンス の議論スペース', '教育委員会は形骸化していないか', 'teacher-school-system'),
  ('room-subject-teaching--community--japanese-language', '国語', 'F. 教科の指導 › 国語 の議論スペース', '国語でAIをどう活用するか', 'subject-teaching'),
  ('room-subject-teaching--community--mathematics', '算数・数学', 'F. 教科の指導 › 算数・数学 の議論スペース', '算数・数学でAIをどう活用するか', 'subject-teaching'),
  ('room-subject-teaching--community--science', '理科', 'F. 教科の指導 › 理科 の議論スペース', '理科でAIをどう活用するか', 'subject-teaching'),
  ('room-subject-teaching--community--social-studies', '社会（地理・歴史・公民）', 'F. 教科の指導 › 社会（地理・歴史・公民） の議論スペース', '社会でAIをどう活用するか', 'subject-teaching'),
  ('room-subject-teaching--community--english-foreign-language', '英語・外国語', 'F. 教科の指導 › 英語・外国語 の議論スペース', '英語でAIをどう活用するか', 'subject-teaching'),
  ('room-subject-teaching--community--moral-education', '道徳', 'F. 教科の指導 › 道徳 の議論スペース', '道徳でAIをどう活用するか', 'subject-teaching'),
  ('room-subject-teaching--community--pe-health', '体育・保健', 'F. 教科の指導 › 体育・保健 の議論スペース', '体育・保健でAIをどう活用するか', 'subject-teaching'),
  ('room-subject-teaching--community--music-art', '音楽・美術', 'F. 教科の指導 › 音楽・美術 の議論スペース', '音楽・美術でAIをどう活用するか', 'subject-teaching'),
  ('room-subject-teaching--community--home-economics-technology', '家庭科・技術', 'F. 教科の指導 › 家庭科・技術 の議論スペース', '技術家庭科でAIをどう活用するか', 'subject-teaching'),
  ('room-subject-teaching--community--integrated-inquiry-time', '総合的な学習／探究の時間', 'F. 教科の指導 › 総合的な学習／探究の時間 の議論スペース', '総合的な学習でAIをどう活用するか', 'subject-teaching'),
  ('room-subject-teaching--community--information-subject', '情報', 'F. 教科の指導 › 情報 の議論スペース', '情報でAIをどう活用するか', 'subject-teaching'),
  ('room-subject-teaching--community--career-guidance', 'キャリア教育・進路指導', 'F. 教科の指導 › キャリア教育・進路指導 の議論スペース', '進路指導でAIをどう活用するか', 'subject-teaching')

) AS v(room_id, room_name, room_desc, weekly_topic, major_slug)
JOIN public.forum_categories c ON c.slug = v.major_slug AND c.is_active = true
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description,
  weekly_topic = EXCLUDED.weekly_topic, category_id = EXCLUDED.category_id,
  sub_category_id = NULL, updated_at = now();


INSERT INTO public.forum_room_topics (id, room_id, title, period_start)
SELECT v.topic_id, v.room_id, v.title, now()
FROM (VALUES
  ('room-ai-technology--community--gen-ai-education-t1', 'room-ai-technology--community--gen-ai-education', '生成AIを児童生徒に何歳から使わせるべきか'),
  ('room-ai-technology--community--gen-ai-education-t2', 'room-ai-technology--community--gen-ai-education', '読書感想文や作文に生成AIを使うのは「ずる」か'),
  ('room-ai-technology--community--gen-ai-education-t3', 'room-ai-technology--community--gen-ai-education', '教師が校務に生成AIを使うことをどこまで認めるか'),
  ('room-ai-technology--community--programming-education-t1', 'room-ai-technology--community--programming-education', 'プログラミングは全児童生徒に必修とすべきか'),
  ('room-ai-technology--community--programming-education-t2', 'room-ai-technology--community--programming-education', 'プログラミング教育の目的は論理的思考か、技能習得か'),
  ('room-ai-technology--community--programming-education-t3', 'room-ai-technology--community--programming-education', 'AIがコードを書く時代にプログラミングを学ぶ意味はあるか'),
  ('room-ai-technology--community--digital-textbook-t1', 'room-ai-technology--community--digital-textbook', '紙の教科書を全面的にデジタルへ移行すべきか'),
  ('room-ai-technology--community--digital-textbook-t2', 'room-ai-technology--community--digital-textbook', 'デジタル教科書は子どもの読解力に影響するか'),
  ('room-ai-technology--community--digital-textbook-t3', 'room-ai-technology--community--digital-textbook', 'デジタルと紙はどう使い分けるべきか'),
  ('room-ai-technology--community--giga-one-device-t1', 'room-ai-technology--community--giga-one-device', 'GIGA端末の家庭への持ち帰りを認めるべきか'),
  ('room-ai-technology--community--giga-one-device-t2', 'room-ai-technology--community--giga-one-device', '端末更新の費用を誰がどう負担すべきか'),
  ('room-ai-technology--community--giga-one-device-t3', 'room-ai-technology--community--giga-one-device', '1人1台端末は本当に学力を高めたか'),
  ('room-ai-technology--community--school-dx-t1', 'room-ai-technology--community--school-dx', '校務支援システムは教員の負担を減らしたか'),
  ('room-ai-technology--community--school-dx-t2', 'room-ai-technology--community--school-dx', '保護者連絡をどこまでデジタル化すべきか'),
  ('room-ai-technology--community--school-dx-t3', 'room-ai-technology--community--school-dx', '出欠・成績データの一元管理はどこまで進めるべきか'),
  ('room-ai-technology--community--data-driven-education-t1', 'room-ai-technology--community--data-driven-education', '学習ログを指導にどこまで活用すべきか'),
  ('room-ai-technology--community--data-driven-education-t2', 'room-ai-technology--community--data-driven-education', '学習データの蓄積は子どもの監視につながらないか'),
  ('room-ai-technology--community--data-driven-education-t3', 'room-ai-technology--community--data-driven-education', 'データに基づく個別指導は教師の勘より優れているか'),
  ('room-ai-technology--community--edtech-adoption-t1', 'room-ai-technology--community--edtech-adoption', '学校はEdTechサービスをどう選定すべきか'),
  ('room-ai-technology--community--edtech-adoption-t2', 'room-ai-technology--community--edtech-adoption', '民間サービスへの依存はどこまで許容されるか'),
  ('room-ai-technology--community--edtech-adoption-t3', 'room-ai-technology--community--edtech-adoption', '無料サービスの利用に潜むリスクをどう考えるか'),
  ('room-ai-technology--community--online-remote-learning-t1', 'room-ai-technology--community--online-remote-learning', 'オンライン授業は対面授業の代わりになるか'),
  ('room-ai-technology--community--online-remote-learning-t2', 'room-ai-technology--community--online-remote-learning', 'ハイブリッド授業をどう設計すべきか'),
  ('room-ai-technology--community--online-remote-learning-t3', 'room-ai-technology--community--online-remote-learning', '不登校児へのオンライン学習を出席扱いにすべきか'),
  ('room-ai-technology--community--ai-literacy-moral-t1', 'room-ai-technology--community--ai-literacy-moral', 'AIリテラシー教育は何歳から始めるべきか'),
  ('room-ai-technology--community--ai-literacy-moral-t2', 'room-ai-technology--community--ai-literacy-moral', 'フェイク情報への対応をどう教えるか'),
  ('room-ai-technology--community--ai-literacy-moral-t3', 'room-ai-technology--community--ai-literacy-moral', '情報モラル教育は学校と家庭のどちらが担うべきか'),
  ('room-ai-technology--community--personalized-learning-t1', 'room-ai-technology--community--personalized-learning', '個別最適化学習は学びを豊かにするか、孤立させるか'),
  ('room-ai-technology--community--personalized-learning-t2', 'room-ai-technology--community--personalized-learning', 'アダプティブ教材と一斉授業をどう両立させるか'),
  ('room-ai-technology--community--personalized-learning-t3', 'room-ai-technology--community--personalized-learning', '「最適化」を誰の基準で決めるべきか'),
  ('room-evaluation-curriculum--community--national-achievement-test-t1', 'room-evaluation-curriculum--community--national-achievement-test', '全国学力調査の結果を学校間で公開すべきか'),
  ('room-evaluation-curriculum--community--national-achievement-test-t2', 'room-evaluation-curriculum--community--national-achievement-test', '学力テストは教育の質を正しく測れるか'),
  ('room-evaluation-curriculum--community--national-achievement-test-t3', 'room-evaluation-curriculum--community--national-achievement-test', 'テスト対策に偏った指導をどう防ぐか'),
  ('room-evaluation-curriculum--community--grade-evaluation-t1', 'room-evaluation-curriculum--community--grade-evaluation', '数値による成績評価は必要か'),
  ('room-evaluation-curriculum--community--grade-evaluation-t2', 'room-evaluation-curriculum--community--grade-evaluation', '観点別評価は現場で機能しているか'),
  ('room-evaluation-curriculum--community--grade-evaluation-t3', 'room-evaluation-curriculum--community--grade-evaluation', '評価の主目的は選別か、成長支援か'),
  ('room-evaluation-curriculum--community--entrance-exam-reform-t1', 'room-evaluation-curriculum--community--entrance-exam-reform', '一発勝負の入試は公平か'),
  ('room-evaluation-curriculum--community--entrance-exam-reform-t2', 'room-evaluation-curriculum--community--entrance-exam-reform', '総合型選抜（旧AO）をどこまで広げるべきか'),
  ('room-evaluation-curriculum--community--entrance-exam-reform-t3', 'room-evaluation-curriculum--community--entrance-exam-reform', '入試にAI・デジタルツールの使用を認めるべきか'),
  ('room-evaluation-curriculum--community--inquiry-pbl-t1', 'room-evaluation-curriculum--community--inquiry-pbl', '探究学習は本当に学力を伸ばすか'),
  ('room-evaluation-curriculum--community--inquiry-pbl-t2', 'room-evaluation-curriculum--community--inquiry-pbl', '探究の成果をどう評価すべきか'),
  ('room-evaluation-curriculum--community--inquiry-pbl-t3', 'room-evaluation-curriculum--community--inquiry-pbl', '教科学習と探究学習のバランスをどう取るか'),
  ('room-evaluation-curriculum--community--steam-education-t1', 'room-evaluation-curriculum--community--steam-education', 'STEAM教育は文系・理系の枠を越えられるか'),
  ('room-evaluation-curriculum--community--steam-education-t2', 'room-evaluation-curriculum--community--steam-education', '芸術（Art）をSTEMに加える意義は何か'),
  ('room-evaluation-curriculum--community--steam-education-t3', 'room-evaluation-curriculum--community--steam-education', 'STEAM教育に必要な教員をどう確保するか'),
  ('room-evaluation-curriculum--community--reading-literacy-t1', 'room-evaluation-curriculum--community--reading-literacy', 'デジタル時代に読解力をどう育てるか'),
  ('room-evaluation-curriculum--community--reading-literacy-t2', 'room-evaluation-curriculum--community--reading-literacy', '読書習慣を学校はどこまで促すべきか'),
  ('room-evaluation-curriculum--community--reading-literacy-t3', 'room-evaluation-curriculum--community--reading-literacy', '「正しく読む力」と「批判的に読む力」のどちらを重視すべきか'),
  ('room-evaluation-curriculum--community--homework-t1', 'room-evaluation-curriculum--community--homework', '宿題は必要か、あるとすればどうあるべきか'),
  ('room-evaluation-curriculum--community--homework-t2', 'room-evaluation-curriculum--community--homework', '宿題の丸つけ・管理は教師が担うべきか'),
  ('room-evaluation-curriculum--community--homework-t3', 'room-evaluation-curriculum--community--homework', '家庭環境による格差を宿題はどう助長するか'),
  ('room-evaluation-curriculum--community--mastery-based-instruction-t1', 'room-evaluation-curriculum--community--mastery-based-instruction', '習熟度別クラス編成は是か非か'),
  ('room-evaluation-curriculum--community--mastery-based-instruction-t2', 'room-evaluation-curriculum--community--mastery-based-instruction', '習熟度別指導は格差を固定しないか'),
  ('room-evaluation-curriculum--community--mastery-based-instruction-t3', 'room-evaluation-curriculum--community--mastery-based-instruction', 'できる子・つまずく子のどちらに重点を置くべきか'),
  ('room-evaluation-curriculum--community--course-of-study-revision-t1', 'room-evaluation-curriculum--community--course-of-study-revision', '学習指導要領は現場の自由度を奪っているか'),
  ('room-evaluation-curriculum--community--course-of-study-revision-t2', 'room-evaluation-curriculum--community--course-of-study-revision', '「詰め込み」と「ゆとり」のバランスをどう取るか'),
  ('room-evaluation-curriculum--community--course-of-study-revision-t3', 'room-evaluation-curriculum--community--course-of-study-revision', '次期改訂で何を増やし、何を減らすべきか'),
  ('room-evaluation-curriculum--community--non-cognitive-skills-t1', 'room-evaluation-curriculum--community--non-cognitive-skills', '非認知能力は学校で育てられるか'),
  ('room-evaluation-curriculum--community--non-cognitive-skills-t2', 'room-evaluation-curriculum--community--non-cognitive-skills', '非認知能力を評価することは可能か、すべきか'),
  ('room-evaluation-curriculum--community--non-cognitive-skills-t3', 'room-evaluation-curriculum--community--non-cognitive-skills', '認知能力と非認知能力のどちらを優先すべきか'),
  ('room-children-rights-discipline--community--school-rules-guidance-t1', 'room-children-rights-discipline--community--school-rules-guidance', '校則をどこまで子ども自身に決めさせるべきか'),
  ('room-children-rights-discipline--community--school-rules-guidance-t2', 'room-children-rights-discipline--community--school-rules-guidance', 'ブラック校則の見直しをどう進めるか'),
  ('room-children-rights-discipline--community--school-rules-guidance-t3', 'room-children-rights-discipline--community--school-rules-guidance', '校則は何のために存在するのか'),
  ('room-children-rights-discipline--community--bullying-prevention-t1', 'room-children-rights-discipline--community--bullying-prevention', 'いじめの「重大事態」をどう線引きするか'),
  ('room-children-rights-discipline--community--bullying-prevention-t2', 'room-children-rights-discipline--community--bullying-prevention', '加害児童への指導と被害児童の保護をどう両立するか'),
  ('room-children-rights-discipline--community--bullying-prevention-t3', 'room-children-rights-discipline--community--bullying-prevention', 'いじめ防止にAI・通報アプリは有効か'),
  ('room-children-rights-discipline--community--school-refusal-support-t1', 'room-children-rights-discipline--community--school-refusal-support', '不登校の子に学校以外の学びをどこまで認めるか'),
  ('room-children-rights-discipline--community--school-refusal-support-t2', 'room-children-rights-discipline--community--school-refusal-support', '「学校復帰」を支援の目標とすべきか'),
  ('room-children-rights-discipline--community--school-refusal-support-t3', 'room-children-rights-discipline--community--school-refusal-support', '不登校を「問題」と捉える見方は適切か'),
  ('room-children-rights-discipline--community--children-rights-voice-t1', 'room-children-rights-discipline--community--children-rights-voice', '子どもの声を学校運営にどう反映させるか'),
  ('room-children-rights-discipline--community--children-rights-voice-t2', 'room-children-rights-discipline--community--children-rights-voice', '校則や行事の決定に子どもをどこまで関与させるか'),
  ('room-children-rights-discipline--community--children-rights-voice-t3', 'room-children-rights-discipline--community--children-rights-voice', '「子どもの権利」と「指導」はどう両立するか'),
  ('room-children-rights-discipline--community--smartphone-sns-t1', 'room-children-rights-discipline--community--smartphone-sns', 'スマホの校内持ち込みを認めるべきか'),
  ('room-children-rights-discipline--community--smartphone-sns-t2', 'room-children-rights-discipline--community--smartphone-sns', 'SNSトラブルに学校はどこまで介入すべきか'),
  ('room-children-rights-discipline--community--smartphone-sns-t3', 'room-children-rights-discipline--community--smartphone-sns', 'デジタルとの付き合い方は誰が教えるべきか'),
  ('room-children-rights-discipline--community--uniform-dress-code-t1', 'room-children-rights-discipline--community--uniform-dress-code', '制服は必要か'),
  ('room-children-rights-discipline--community--uniform-dress-code-t2', 'room-children-rights-discipline--community--uniform-dress-code', 'ジェンダーレス制服をどう導入するか'),
  ('room-children-rights-discipline--community--uniform-dress-code-t3', 'room-children-rights-discipline--community--uniform-dress-code', '服装の自由は学習に影響するか'),
  ('room-children-rights-discipline--community--club-activities-t1', 'room-children-rights-discipline--community--club-activities', '部活動の強制加入は是か非か'),
  ('room-children-rights-discipline--community--club-activities-t2', 'room-children-rights-discipline--community--club-activities', '勝利至上主義をどう見直すか'),
  ('room-children-rights-discipline--community--club-activities-t3', 'room-children-rights-discipline--community--club-activities', '部活動は学校教育の一部であるべきか'),
  ('room-children-rights-discipline--community--mental-health-t1', 'room-children-rights-discipline--community--mental-health', '学校はメンタルヘルスにどこまで踏み込むべきか'),
  ('room-children-rights-discipline--community--mental-health-t2', 'room-children-rights-discipline--community--mental-health', 'スクールカウンセラーの役割をどう位置づけるか'),
  ('room-children-rights-discipline--community--mental-health-t3', 'room-children-rights-discipline--community--mental-health', '「休む権利」を子どもに認めるべきか'),
  ('room-children-rights-discipline--community--child-abuse-protection-t1', 'room-children-rights-discipline--community--child-abuse-protection', '学校はどこまで家庭に介入すべきか'),
  ('room-children-rights-discipline--community--child-abuse-protection-t2', 'room-children-rights-discipline--community--child-abuse-protection', '虐待の早期発見に学校は何ができるか'),
  ('room-children-rights-discipline--community--child-abuse-protection-t3', 'room-children-rights-discipline--community--child-abuse-protection', '通告の判断を教師が担う負担をどう考えるか'),
  ('room-children-rights-discipline--community--corporal-punishment-guidance-t1', 'room-children-rights-discipline--community--corporal-punishment-guidance', '厳しい指導と体罰の線引きをどこに置くか'),
  ('room-children-rights-discipline--community--corporal-punishment-guidance-t2', 'room-children-rights-discipline--community--corporal-punishment-guidance', '「指導死」を防ぐために何が必要か'),
  ('room-children-rights-discipline--community--corporal-punishment-guidance-t3', 'room-children-rights-discipline--community--corporal-punishment-guidance', '毅然とした指導はどこまで許されるか'),
  ('room-diversity-inclusion--community--inclusive-special-needs-t1', 'room-diversity-inclusion--community--inclusive-special-needs', '障害のある子への合理的配慮をどこまで提供すべきか'),
  ('room-diversity-inclusion--community--inclusive-special-needs-t2', 'room-diversity-inclusion--community--inclusive-special-needs', '通常学級と特別支援学級の学びの場をどう考えるか'),
  ('room-diversity-inclusion--community--inclusive-special-needs-t3', 'room-diversity-inclusion--community--inclusive-special-needs', 'インクルーシブ教育を支える人員をどう確保するか'),
  ('room-diversity-inclusion--community--multicultural-foreign-roots-t1', 'room-diversity-inclusion--community--multicultural-foreign-roots', '日本語指導をどう充実させるか'),
  ('room-diversity-inclusion--community--multicultural-foreign-roots-t2', 'room-diversity-inclusion--community--multicultural-foreign-roots', '母語・母文化の保持を学校はどこまで支援すべきか'),
  ('room-diversity-inclusion--community--multicultural-foreign-roots-t3', 'room-diversity-inclusion--community--multicultural-foreign-roots', '多言語対応をどこまで進めるべきか'),
  ('room-diversity-inclusion--community--gifted-talent-education-t1', 'room-diversity-inclusion--community--gifted-talent-education', '特異な才能のある子への支援は必要か'),
  ('room-diversity-inclusion--community--gifted-talent-education-t2', 'room-diversity-inclusion--community--gifted-talent-education', '才能教育は「えこひいき」か「合理的配慮」か'),
  ('room-diversity-inclusion--community--gifted-talent-education-t3', 'room-diversity-inclusion--community--gifted-talent-education', '飛び級を柔軟に認めるべきか'),
  ('room-diversity-inclusion--community--educational-poverty-gap-t1', 'room-diversity-inclusion--community--educational-poverty-gap', '貧困家庭の子の学習支援を学校はどこまで担うべきか'),
  ('room-diversity-inclusion--community--educational-poverty-gap-t2', 'room-diversity-inclusion--community--educational-poverty-gap', '教育格差の是正に何が最も有効か'),
  ('room-diversity-inclusion--community--educational-poverty-gap-t3', 'room-diversity-inclusion--community--educational-poverty-gap', '無償化はどこまで進めるべきか'),
  ('room-diversity-inclusion--community--gender-education-t1', 'room-diversity-inclusion--community--gender-education', '名簿・呼称・制服のジェンダー配慮をどう進めるか'),
  ('room-diversity-inclusion--community--gender-education-t2', 'room-diversity-inclusion--community--gender-education', '「男女平等」と「区別」の線引きをどこに置くか'),
  ('room-diversity-inclusion--community--gender-education-t3', 'room-diversity-inclusion--community--gender-education', 'ジェンダー教育はどこまで踏み込むべきか'),
  ('room-diversity-inclusion--community--sex-education-t1', 'room-diversity-inclusion--community--sex-education', '性教育をどこまで踏み込んで行うべきか'),
  ('room-diversity-inclusion--community--sex-education-t2', 'room-diversity-inclusion--community--sex-education', '「はどめ規定」をどう考えるか'),
  ('room-diversity-inclusion--community--sex-education-t3', 'room-diversity-inclusion--community--sex-education', '性の多様性をどう教えるか'),
  ('room-diversity-inclusion--community--multicultural-coexistence-t1', 'room-diversity-inclusion--community--multicultural-coexistence', '多文化共生をどう学校文化に根づかせるか'),
  ('room-diversity-inclusion--community--multicultural-coexistence-t2', 'room-diversity-inclusion--community--multicultural-coexistence', '宗教・文化的配慮（給食・服装等）をどこまで行うか'),
  ('room-diversity-inclusion--community--multicultural-coexistence-t3', 'room-diversity-inclusion--community--multicultural-coexistence', '「同化」と「共生」の違いをどう考えるか'),
  ('room-diversity-inclusion--community--night-junior-high-t1', 'room-diversity-inclusion--community--night-junior-high', '学び直しの機会をどう保障するか'),
  ('room-diversity-inclusion--community--night-junior-high-t2', 'room-diversity-inclusion--community--night-junior-high', '夜間中学を全自治体に設置すべきか'),
  ('room-diversity-inclusion--community--night-junior-high-t3', 'room-diversity-inclusion--community--night-junior-high', '義務教育未修了者への支援をどう広げるか'),
  ('room-diversity-inclusion--community--medical-care-children-t1', 'room-diversity-inclusion--community--medical-care-children', '医療的ケア児の通常学級での学びをどう支えるか'),
  ('room-diversity-inclusion--community--medical-care-children-t2', 'room-diversity-inclusion--community--medical-care-children', '看護師・人員配置をどう確保するか'),
  ('room-diversity-inclusion--community--medical-care-children-t3', 'room-diversity-inclusion--community--medical-care-children', '保護者の付き添い負担をどう軽減するか'),
  ('room-diversity-inclusion--community--diverse-learning-places-t1', 'room-diversity-inclusion--community--diverse-learning-places', 'フリースクールを正式な学びの場と認めるべきか'),
  ('room-diversity-inclusion--community--diverse-learning-places-t2', 'room-diversity-inclusion--community--diverse-learning-places', 'ホームスクーリングをどこまで認めるか'),
  ('room-diversity-inclusion--community--diverse-learning-places-t3', 'room-diversity-inclusion--community--diverse-learning-places', '「学校に通う」以外の選択肢をどう保障するか'),
  ('room-teacher-school-system--community--teacher-work-style-reform-t1', 'room-teacher-school-system--community--teacher-work-style-reform', '教員の働き方改革のために何を削るべきか'),
  ('room-teacher-school-system--community--teacher-work-style-reform-t2', 'room-teacher-school-system--community--teacher-work-style-reform', '残業の上限規制を実効性あるものにするには'),
  ('room-teacher-school-system--community--teacher-work-style-reform-t3', 'room-teacher-school-system--community--teacher-work-style-reform', '「子どものため」という言葉が長時間労働を生んでいないか'),
  ('room-teacher-school-system--community--teacher-shortage-recruitment-t1', 'room-teacher-school-system--community--teacher-shortage-recruitment', '教員不足をどう解消するか'),
  ('room-teacher-school-system--community--teacher-shortage-recruitment-t2', 'room-teacher-school-system--community--teacher-shortage-recruitment', '社会人・民間人材の登用をどう進めるか'),
  ('room-teacher-school-system--community--teacher-shortage-recruitment-t3', 'room-teacher-school-system--community--teacher-shortage-recruitment', '教員の待遇改善に何が最も必要か'),
  ('room-teacher-school-system--community--teacher-licensure-t1', 'room-teacher-school-system--community--teacher-licensure', '教員免許制度は今のままでよいか'),
  ('room-teacher-school-system--community--teacher-licensure-t2', 'room-teacher-school-system--community--teacher-licensure', '教職課程に何を加え、何を減らすべきか'),
  ('room-teacher-school-system--community--teacher-licensure-t3', 'room-teacher-school-system--community--teacher-licensure', '免許更新制の廃止は妥当だったか'),
  ('room-teacher-school-system--community--teacher-training-t1', 'room-teacher-school-system--community--teacher-training', '教員研修は教育の質向上に役立っているか'),
  ('room-teacher-school-system--community--teacher-training-t2', 'room-teacher-school-system--community--teacher-training', '研修の時間をどう確保するか'),
  ('room-teacher-school-system--community--teacher-training-t3', 'room-teacher-school-system--community--teacher-training', '研修内容を誰が決めるべきか'),
  ('room-teacher-school-system--community--club-community-transition-t1', 'room-teacher-school-system--community--club-community-transition', '部活動の地域移行を進めるべきか'),
  ('room-teacher-school-system--community--club-community-transition-t2', 'room-teacher-school-system--community--club-community-transition', '地域移行の費用を誰が負担すべきか'),
  ('room-teacher-school-system--community--club-community-transition-t3', 'room-teacher-school-system--community--club-community-transition', '地域移行で部活動の教育的意義は保たれるか'),
  ('room-teacher-school-system--community--school-consolidation-t1', 'room-teacher-school-system--community--school-consolidation', '小規模校の統廃合をどう判断すべきか'),
  ('room-teacher-school-system--community--school-consolidation-t2', 'room-teacher-school-system--community--school-consolidation', '学校は地域コミュニティの核として残すべきか'),
  ('room-teacher-school-system--community--school-consolidation-t3', 'room-teacher-school-system--community--school-consolidation', '統廃合による通学負担をどう考えるか'),
  ('room-teacher-school-system--community--school-family-community-t1', 'room-teacher-school-system--community--school-family-community', '学校・家庭・地域の役割分担をどう設計するか'),
  ('room-teacher-school-system--community--school-family-community-t2', 'room-teacher-school-system--community--school-family-community', 'コミュニティ・スクールは機能しているか'),
  ('room-teacher-school-system--community--school-family-community-t3', 'room-teacher-school-system--community--school-family-community', '地域人材の活用をどこまで進めるべきか'),
  ('room-teacher-school-system--community--parent-demands-t1', 'room-teacher-school-system--community--parent-demands', '過剰な保護者要求に学校はどこまで応じるべきか'),
  ('room-teacher-school-system--community--parent-demands-t2', 'room-teacher-school-system--community--parent-demands', '保護者対応の負担を誰がどう支えるか'),
  ('room-teacher-school-system--community--parent-demands-t3', 'room-teacher-school-system--community--parent-demands', '学校と保護者の「信頼関係」をどう築くか'),
  ('room-teacher-school-system--community--principal-leadership-t1', 'room-teacher-school-system--community--principal-leadership', '管理職に求められるリーダーシップとは何か'),
  ('room-teacher-school-system--community--principal-leadership-t2', 'room-teacher-school-system--community--principal-leadership', '管理職のなり手不足をどう解消するか'),
  ('room-teacher-school-system--community--principal-leadership-t3', 'room-teacher-school-system--community--principal-leadership', '学校の意思決定をどこまで民主化すべきか'),
  ('room-teacher-school-system--community--education-governance-t1', 'room-teacher-school-system--community--education-governance', '教育委員会は形骸化していないか'),
  ('room-teacher-school-system--community--education-governance-t2', 'room-teacher-school-system--community--education-governance', '教育の政治的中立性をどう保つか'),
  ('room-teacher-school-system--community--education-governance-t3', 'room-teacher-school-system--community--education-governance', '現場の裁量と行政の統制のバランスをどう取るか'),
  ('room-subject-teaching--community--japanese-language-t1', 'room-subject-teaching--community--japanese-language', '国語でAIをどう活用するか'),
  ('room-subject-teaching--community--japanese-language-t2', 'room-subject-teaching--community--japanese-language', '漢字の手書き指導はどこまで必要か'),
  ('room-subject-teaching--community--japanese-language-t3', 'room-subject-teaching--community--japanese-language', '話す・書く力をどう評価するか'),
  ('room-subject-teaching--community--mathematics-t1', 'room-subject-teaching--community--mathematics', '算数・数学でAIをどう活用するか'),
  ('room-subject-teaching--community--mathematics-t2', 'room-subject-teaching--community--mathematics', '電卓・数式アプリを授業でどこまで使わせるか'),
  ('room-subject-teaching--community--mathematics-t3', 'room-subject-teaching--community--mathematics', '「なぜ数学を学ぶのか」にどう答えるか'),
  ('room-subject-teaching--community--science-t1', 'room-subject-teaching--community--science', '理科でAIをどう活用するか'),
  ('room-subject-teaching--community--science-t2', 'room-subject-teaching--community--science', '知識の習得と探究的な学びのバランスをどう取るか'),
  ('room-subject-teaching--community--science-t3', 'room-subject-teaching--community--science', '理科離れをどう食い止めるか'),
  ('room-subject-teaching--community--social-studies-t1', 'room-subject-teaching--community--social-studies', '社会でAIをどう活用するか'),
  ('room-subject-teaching--community--social-studies-t2', 'room-subject-teaching--community--social-studies', '現代の論争的なテーマをどこまで扱うべきか'),
  ('room-subject-teaching--community--social-studies-t3', 'room-subject-teaching--community--social-studies', '主権者教育・シティズンシップをどう育てるか'),
  ('room-subject-teaching--community--english-foreign-language-t1', 'room-subject-teaching--community--english-foreign-language', '英語でAIをどう活用するか'),
  ('room-subject-teaching--community--english-foreign-language-t2', 'room-subject-teaching--community--english-foreign-language', '文法・読解と会話のどちらを優先すべきか'),
  ('room-subject-teaching--community--english-foreign-language-t3', 'room-subject-teaching--community--english-foreign-language', 'AI翻訳がある時代に英語を学ぶ意味は何か'),
  ('room-subject-teaching--community--moral-education-t1', 'room-subject-teaching--community--moral-education', '道徳でAIをどう活用するか'),
  ('room-subject-teaching--community--moral-education-t2', 'room-subject-teaching--community--moral-education', '「正解のある道徳」になっていないか'),
  ('room-subject-teaching--community--moral-education-t3', 'room-subject-teaching--community--moral-education', '価値観の多様性をどう扱うか'),
  ('room-subject-teaching--community--pe-health-t1', 'room-subject-teaching--community--pe-health', '体育・保健でAIをどう活用するか'),
  ('room-subject-teaching--community--pe-health-t2', 'room-subject-teaching--community--pe-health', '競争・順位づけは体育に必要か'),
  ('room-subject-teaching--community--pe-health-t3', 'room-subject-teaching--community--pe-health', '保健（性・健康・安全）をどこまで踏み込むか'),
  ('room-subject-teaching--community--music-art-t1', 'room-subject-teaching--community--music-art', '音楽・美術でAIをどう活用するか'),
  ('room-subject-teaching--community--music-art-t2', 'room-subject-teaching--community--music-art', '技能の習得と自由な表現のどちらを重視すべきか'),
  ('room-subject-teaching--community--music-art-t3', 'room-subject-teaching--community--music-art', '芸術教育の時間削減をどう考えるか'),
  ('room-subject-teaching--community--home-economics-technology-t1', 'room-subject-teaching--community--home-economics-technology', '技術家庭科でAIをどう活用するか'),
  ('room-subject-teaching--community--home-economics-technology-t2', 'room-subject-teaching--community--home-economics-technology', '生活スキルの教育を学校はどこまで担うべきか'),
  ('room-subject-teaching--community--home-economics-technology-t3', 'room-subject-teaching--community--home-economics-technology', '技術科とプログラミング・ものづくりをどう統合するか'),
  ('room-subject-teaching--community--integrated-inquiry-time-t1', 'room-subject-teaching--community--integrated-inquiry-time', '総合的な学習でAIをどう活用するか'),
  ('room-subject-teaching--community--integrated-inquiry-time-t2', 'room-subject-teaching--community--integrated-inquiry-time', '教科横断の学びをどう設計するか'),
  ('room-subject-teaching--community--integrated-inquiry-time-t3', 'room-subject-teaching--community--integrated-inquiry-time', '成果をどう評価し、何を学びとするか'),
  ('room-subject-teaching--community--information-subject-t1', 'room-subject-teaching--community--information-subject', '情報でAIをどう活用するか'),
  ('room-subject-teaching--community--information-subject-t2', 'room-subject-teaching--community--information-subject', '情報モラルと情報技術のどちらを重視すべきか'),
  ('room-subject-teaching--community--information-subject-t3', 'room-subject-teaching--community--information-subject', '大学入試科目「情報」をどう位置づけるか'),
  ('room-subject-teaching--community--career-guidance-t1', 'room-subject-teaching--community--career-guidance', '進路指導でAIをどう活用するか'),
  ('room-subject-teaching--community--career-guidance-t2', 'room-subject-teaching--community--career-guidance', '進路指導は「偏差値」から脱却できるか'),
  ('room-subject-teaching--community--career-guidance-t3', 'room-subject-teaching--community--career-guidance', '変化の激しい時代に何を基準に進路を示すか')

) AS v(topic_id, room_id, title)
ON CONFLICT (id) DO UPDATE SET room_id = EXCLUDED.room_id, title = EXCLUDED.title;


UPDATE public.forum_rooms SET hot_override = true, updated_at = now() WHERE id IN (
  'room-ai-technology--community--digital-textbook',
  'room-ai-technology--community--edtech-adoption',
  'room-ai-technology--community--ai-literacy-moral',
  'room-ai-technology--community--personalized-learning',
  'room-evaluation-curriculum--community--inquiry-pbl',
  'room-evaluation-curriculum--community--homework',
  'room-evaluation-curriculum--community--course-of-study-revision',
  'room-evaluation-curriculum--community--non-cognitive-skills',
  'room-children-rights-discipline--community--school-rules-guidance',
  'room-children-rights-discipline--community--bullying-prevention',
  'room-children-rights-discipline--community--school-refusal-support',
  'room-children-rights-discipline--community--smartphone-sns',
  'room-diversity-inclusion--community--inclusive-special-needs',
  'room-diversity-inclusion--community--multicultural-foreign-roots',
  'room-teacher-school-system--community--teacher-work-style-reform',
  'room-teacher-school-system--community--school-consolidation',
  'room-subject-teaching--community--japanese-language',
  'room-subject-teaching--community--mathematics',
  'room-subject-teaching--community--science',
  'room-subject-teaching--community--social-studies',
  'room-subject-teaching--community--english-foreign-language',
  'room-subject-teaching--community--moral-education',
  'room-subject-teaching--community--pe-health',
  'room-subject-teaching--community--music-art',
  'room-subject-teaching--community--home-economics-technology',
  'room-subject-teaching--community--integrated-inquiry-time',
  'room-subject-teaching--community--information-subject',
  'room-subject-teaching--community--career-guidance'
);

COMMIT;
