-- CSV由来シード投稿を論点（topic_id）ごとに再投入
-- forum_room_topics.id（{room_id}-t1/t2/t3）と一致させる
-- 前提: 20260610000000_idobata_community_rooms_from_csv.sql で論点マスタが入っていること

CREATE OR REPLACE FUNCTION app_private.apply_forum_post_author_defaults()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  actor_id UUID;
  profile_name TEXT;
  profile_ai_kentei_passed BOOLEAN;
BEGIN
  actor_id := COALESCE(auth.uid(), NEW.author_id);
  IF actor_id IS NULL THEN
    IF NEW.author_name IS NULL OR btrim(NEW.author_name) = '' THEN
      RAISE EXCEPTION 'author_name required for anonymous forum post';
    END IF;
    NEW.author_id := NULL;
    RETURN NEW;
  END IF;
  SELECT name, ai_kentei_passed
  INTO profile_name, profile_ai_kentei_passed
  FROM public."Profile"
  WHERE id = actor_id;
  IF profile_name IS NULL THEN
    RAISE EXCEPTION 'profile not found for forum post author';
  END IF;
  NEW.author_id := actor_id;
  NEW.author_name := profile_name;
  NEW.author_role := app_private.forum_author_role_for_profile(actor_id);
  NEW.ai_kentei_passed := COALESCE(profile_ai_kentei_passed, FALSE);
  RETURN NEW;
END;
$$;

-- 旧シード（topic_id NULL）を削除
DELETE FROM public.forum_posts
WHERE author_id IS NULL
  AND room_id LIKE 'room-%--community--%'
  AND body NOT LIKE '[AI]%';

INSERT INTO public.forum_posts
  (id, room_id, topic_id, author_name, author_role, body, ai_kentei_passed, created_at)
VALUES
  (gen_random_uuid(), 'room-ai-technology--community--digital-textbook', 'room-ai-technology--community--digital-textbook-t1', 'ぱんだ', '小学校教員', '全面移行には反対です。紙をめくって読む集中力も大事に育てたい。', false, now() - interval '0 minutes'),
  (gen_random_uuid(), 'room-ai-technology--community--digital-textbook', 'room-ai-technology--community--digital-textbook-t1', 'ふじやま', '校務DX担当', 'デジタルは検索や動画連動、書き込みの共有など利点が多い一方、長時間の画面で目が疲れる、通信トラブルで授業が止まるといった不安も根強い。まずは教科や場面を限った段階的な併用から始めるのが現実的だと思います。', false, now() - interval '37 minutes'),
  (gen_random_uuid(), 'room-ai-technology--community--digital-textbook', 'room-ai-technology--community--digital-textbook-t1', 'コタロー', '大学院生', '紙とデジタルでは記憶の定着の仕方が違うという研究もあります。使い分ける前提で議論したいです。', false, now() - interval '74 minutes'),
  (gen_random_uuid(), 'room-ai-technology--community--digital-textbook', 'room-ai-technology--community--digital-textbook-t1', 'ゆずぽん', '3児の母', '家庭のWi-Fi環境に差があるので、全面移行は格差を広げないか心配です。', false, now() - interval '111 minutes'),
  (gen_random_uuid(), 'room-ai-technology--community--edtech-adoption', 'room-ai-technology--community--edtech-adoption-t1', 'テック岡', '情報科', '価格や知名度ではなく、子どものデータがどう守られるかを最優先に選ぶべきです。', false, now() - interval '148 minutes'),
  (gen_random_uuid(), 'room-ai-technology--community--edtech-adoption', 'room-ai-technology--community--edtech-adoption-t1', 'かもめ', '教頭', '現場が使いこなせるかが一番の問題。', false, now() - interval '185 minutes'),
  (gen_random_uuid(), 'room-ai-technology--community--ai-literacy-moral', 'room-ai-technology--community--ai-literacy-moral-t1', 'ぱんだ', '小学校教員', '低学年からでも『鵜呑みにしない』姿勢は教えられます。', false, now() - interval '222 minutes'),
  (gen_random_uuid(), 'room-ai-technology--community--ai-literacy-moral', 'room-ai-technology--community--ai-literacy-moral-t1', 'ノリック', 'ICT支援員', '年齢で線を引くより、デバイスに触れ始めた時点が開始点だと思います。幼くてもAIの答えが必ずしも正しくないこと、個人情報を打ち込まないことは、具体例で繰り返し伝えれば十分に伝わります。', false, now() - interval '259 minutes'),
  (gen_random_uuid(), 'room-ai-technology--community--ai-literacy-moral', 'room-ai-technology--community--ai-literacy-moral-t1', 'とんかつ', '保護者会長', '家庭でスマホを使い始める年齢が下がっている以上、学校の指導が追いついていないのが実情です。', false, now() - interval '296 minutes'),
  (gen_random_uuid(), 'room-ai-technology--community--personalized-learning', 'room-ai-technology--community--personalized-learning-t1', 'カエル先生', '中学数学', '一人ひとりに合った進度で学べるのは大きな利点。つまずきを早く見つけられます。', false, now() - interval '333 minutes'),
  (gen_random_uuid(), 'room-ai-technology--community--personalized-learning', 'room-ai-technology--community--personalized-learning-t1', 'はるか', '探究コーディネーター', 'ただ画面に向かう時間が増えると、友達と話し合いながら学ぶ機会が減る。最適化は道具として使い、人と関わる学びと組み合わせてこそ豊かになる。孤立させるかどうかは教員の設計次第だと思います。', false, now() - interval '370 minutes'),
  (gen_random_uuid(), 'room-ai-technology--community--personalized-learning', 'room-ai-technology--community--personalized-learning-t1', 'コタロー', '大学院生', '『最適』を誰が決めるのかが気になります。', false, now() - interval '407 minutes'),
  (gen_random_uuid(), 'room-evaluation-curriculum--community--inquiry-pbl', 'room-evaluation-curriculum--community--inquiry-pbl-t1', 'はるか', '探究コーディネーター', 'テストの点だけ見れば効果はすぐ表れにくい。でも『自分で問いを立てて調べる』経験は、長い目で学ぶ意欲や思考力につながります。何を学力と呼ぶかの議論が先です。', false, now() - interval '444 minutes'),
  (gen_random_uuid(), 'room-evaluation-curriculum--community--inquiry-pbl', 'room-evaluation-curriculum--community--inquiry-pbl-t1', 'ごましお', '主幹教諭', 'やりっぱなしにせず、振り返りまでが探究です。', false, now() - interval '481 minutes'),
  (gen_random_uuid(), 'room-evaluation-curriculum--community--inquiry-pbl', 'room-evaluation-curriculum--community--inquiry-pbl-t1', 'とんかつ', '保護者会長', '受験を控えると、探究に時間を割く余裕があるのか不安になるのが親の本音です。', false, now() - interval '518 minutes'),
  (gen_random_uuid(), 'room-evaluation-curriculum--community--homework', 'room-evaluation-curriculum--community--homework-t1', 'うめ子', '高校国語', '一律の宿題は、もう時代に合わないと思います。', false, now() - interval '555 minutes'),
  (gen_random_uuid(), 'room-evaluation-curriculum--community--homework', 'room-evaluation-curriculum--community--homework-t1', 'つばさ', 'NPO職員', '家庭のサポート力に差がある以上、宿題前提の設計は格差を広げます。学校内で完結させたい。', false, now() - interval '592 minutes'),
  (gen_random_uuid(), 'room-evaluation-curriculum--community--homework', 'room-evaluation-curriculum--community--homework-t1', 'ぱんだ', '小学校教員', '全部なくすのではなく、子どもが内容を選べる『自学』にすると、やらされ感が減って力もつく。丸つけや管理を全部教員が背負わず、AIや相互チェックを取り入れる工夫も要ります。', false, now() - interval '629 minutes'),
  (gen_random_uuid(), 'room-evaluation-curriculum--community--homework', 'room-evaluation-curriculum--community--homework-t1', 'ゆずぽん', '3児の母', '共働きだと、見てあげる時間がないのが現実です。', false, now() - interval '666 minutes'),
  (gen_random_uuid(), 'room-evaluation-curriculum--community--course-of-study-revision', 'room-evaluation-curriculum--community--course-of-study-revision-t1', 'タケじい', '元校長', '細かく決まっているからこそ、どの学校でも一定の質が保たれる面もあります。', false, now() - interval '703 minutes'),
  (gen_random_uuid(), 'room-evaluation-curriculum--community--course-of-study-revision', 'room-evaluation-curriculum--community--course-of-study-revision-t1', 'ごましお', '主幹教諭', '内容が多すぎて『こなす』だけで精一杯になり、目の前の子に合わせて工夫する余白がない。最低限の核を示したうえで、あとは現場に委ねるくらいでちょうどいいと感じます。', false, now() - interval '740 minutes'),
  (gen_random_uuid(), 'room-evaluation-curriculum--community--course-of-study-revision', 'room-evaluation-curriculum--community--course-of-study-revision-t1', 'カエル先生', '中学数学', '自由度より、まず時数と内容のバランスを見直してほしいです。', false, now() - interval '777 minutes'),
  (gen_random_uuid(), 'room-evaluation-curriculum--community--course-of-study-revision', 'room-evaluation-curriculum--community--course-of-study-revision-t1', 'みずき', '教育ライター', '国の方針があるから保護者も安心できる面はある。自由と標準の線引きが難しいですね。', false, now() - interval '814 minutes'),
  (gen_random_uuid(), 'room-evaluation-curriculum--community--non-cognitive-skills', 'room-evaluation-curriculum--community--non-cognitive-skills-t1', 'まろん', '養護教諭', '数値化しにくいだけで、毎日の関わりの中で確かに育っています。', false, now() - interval '851 minutes'),
  (gen_random_uuid(), 'room-evaluation-curriculum--community--non-cognitive-skills', 'room-evaluation-curriculum--community--non-cognitive-skills-t1', 'ごましお', '主幹教諭', '協働や粘り強さは、行事や日々のトラブル対応の中で自然に育つもの。ただ『育てている』と意識せず流してしまうと、子どもによって経験に差が出る。意図的に場を設計することが学校の役割だと思います。', false, now() - interval '888 minutes'),
  (gen_random_uuid(), 'room-evaluation-curriculum--community--non-cognitive-skills', 'room-evaluation-curriculum--community--non-cognitive-skills-t1', 'ゆずぽん', '3児の母', '家庭のしつけと学校教育の境界が曖昧で、どこまで踏み込むか迷います。', false, now() - interval '925 minutes'),
  (gen_random_uuid(), 'room-children-rights-discipline--community--school-rules-guidance', 'room-children-rights-discipline--community--school-rules-guidance-t1', 'あおい', '生徒会担当', '自分たちで決めたルールは守る意識も高まる。生徒会で議論する価値は大きいです。', false, now() - interval '962 minutes'),
  (gen_random_uuid(), 'room-children-rights-discipline--community--school-rules-guidance', 'room-children-rights-discipline--community--school-rules-guidance-t1', 'かもめ', '教頭', '全部任せるのではなく、安全に関わる線は大人が守る。', false, now() - interval '999 minutes'),
  (gen_random_uuid(), 'room-children-rights-discipline--community--school-rules-guidance', 'room-children-rights-discipline--community--school-rules-guidance-t1', 'れきお', '社会科', '『なぜこの校則があるのか』を子どもと一緒に問い直すことそのものが、生きた主権者教育になる。守らせる対象ではなく考える教材として扱えば、理不尽な決まりも自然と整理されていくと思います。', false, now() - interval '1036 minutes'),
  (gen_random_uuid(), 'room-children-rights-discipline--community--school-rules-guidance', 'room-children-rights-discipline--community--school-rules-guidance-t1', 'ミント', '中2女子', '中学のとき、意味のない校則に疑問でした。', false, now() - interval '1073 minutes'),
  (gen_random_uuid(), 'room-children-rights-discipline--community--bullying-prevention', 'room-children-rights-discipline--community--bullying-prevention-t1', '森のくま', 'スクールカウンセラー', '『重大かどうか』を後から判断していては手遅れになる。本人が苦痛を訴えた時点で初期対応に動くのが原則で、線引きの議論が初動を遅らせる口実になってはいけません。', false, now() - interval '1110 minutes'),
  (gen_random_uuid(), 'room-children-rights-discipline--community--bullying-prevention', 'room-children-rights-discipline--community--bullying-prevention-t1', 'ごましお', '主幹教諭', '組織で抱え、担任一人に背負わせないことが第一。', false, now() - interval '1147 minutes'),
  (gen_random_uuid(), 'room-children-rights-discipline--community--bullying-prevention', 'room-children-rights-discipline--community--bullying-prevention-t1', 'とんかつ', '保護者会長', '保護者としては、基準より『すぐ動いてくれるか』を一番見ています。', false, now() - interval '1184 minutes'),
  (gen_random_uuid(), 'room-children-rights-discipline--community--school-refusal-support', 'room-children-rights-discipline--community--school-refusal-support-t1', 'ルナ', '不登校経験者', '学校がすべてではない、と私は経験から思います。', false, now() - interval '1221 minutes'),
  (gen_random_uuid(), 'room-children-rights-discipline--community--school-refusal-support', 'room-children-rights-discipline--community--school-refusal-support-t1', 'ヒナタ', 'フリースクール代表', 'フリースクールやオンライン学習を出席として柔軟に認める動きは広がっている。大事なのは『どこで学ぶか』より『学び続けられるか』。本人が安心できる場を複数用意することが先だと思います。', false, now() - interval '1258 minutes'),
  (gen_random_uuid(), 'room-children-rights-discipline--community--school-refusal-support', 'room-children-rights-discipline--community--school-refusal-support-t1', 'ぱんだ', '小学校教員', '認める一方で、学びの機会が長期間失われないよう見守るバランスが難しいです。', false, now() - interval '1295 minutes'),
  (gen_random_uuid(), 'room-children-rights-discipline--community--school-refusal-support', 'room-children-rights-discipline--community--school-refusal-support-t1', 'ゆずぽん', '3児の母', '選択肢があるだけで親子の安心感が違います。', false, now() - interval '1332 minutes'),
  (gen_random_uuid(), 'room-children-rights-discipline--community--smartphone-sns', 'room-children-rights-discipline--community--smartphone-sns-t1', 'ふじやま', '校務DX担当', '災害時の連絡手段として、持ち込み自体は認めざるを得ない時代だと思います。', false, now() - interval '1369 minutes'),
  (gen_random_uuid(), 'room-children-rights-discipline--community--smartphone-sns', 'room-children-rights-discipline--community--smartphone-sns-t1', 'かもめ', '教頭', '授業中の扱いをどう管理するかが本丸です。', false, now() - interval '1406 minutes'),
  (gen_random_uuid(), 'room-children-rights-discipline--community--smartphone-sns', 'room-children-rights-discipline--community--smartphone-sns-t1', 'テック岡', '情報科', '全面禁止は隠れて使う子を増やすだけ。むしろ『どう付き合うか』を学ぶ教材として、ルールを子どもと一緒に作る方が教育的だと思います。取り上げて終わりにしないことが大事です。', false, now() - interval '1443 minutes'),
  (gen_random_uuid(), 'room-children-rights-discipline--community--smartphone-sns', 'room-children-rights-discipline--community--smartphone-sns-t1', 'とんかつ', '保護者会長', '持たせる以上、家庭でのルール作りも要りますね。', false, now() - interval '1480 minutes'),
  (gen_random_uuid(), 'room-diversity-inclusion--community--inclusive-special-needs', 'room-diversity-inclusion--community--inclusive-special-needs-t1', 'クローバー', '特別支援', '理念を支えるのは結局人員。介助員や支援員の配置を拡充しない限り、『配慮』が現場の負担増だけで終わってしまう。どこから予算を持ってくるかまで踏み込んで議論したいです。', false, now() - interval '1517 minutes'),
  (gen_random_uuid(), 'room-diversity-inclusion--community--inclusive-special-needs', 'room-diversity-inclusion--community--inclusive-special-needs-t1', 'くるみ', '放デイ職員', '『特別扱い』ではなく当然の権利だと捉えたい。', false, now() - interval '1554 minutes'),
  (gen_random_uuid(), 'room-diversity-inclusion--community--inclusive-special-needs', 'room-diversity-inclusion--community--inclusive-special-needs-t1', 'ぱんだ', '小学校教員', '周りの子への説明や理解づくりもセットでないと、かえって本人が浮いてしまいます。', false, now() - interval '1591 minutes'),
  (gen_random_uuid(), 'room-diversity-inclusion--community--multicultural-foreign-roots', 'room-diversity-inclusion--community--multicultural-foreign-roots-t1', 'ふじやま', '校務DX担当', '翻訳AIや多言語教材で、少人数の言語にも現実的に対応できる時代になりました。', false, now() - interval '1628 minutes'),
  (gen_random_uuid(), 'room-diversity-inclusion--community--multicultural-foreign-roots', 'room-diversity-inclusion--community--multicultural-foreign-roots-t1', 'セナ', '帰国子女', 'ツールで日常会話は回っても、教科の学習言語や進路の相談は別物。専門の加配教員を増やさないと、結局その子が進学でつまずく。日本語を身につける支援とセットで進めることが欠かせないと思います。', false, now() - interval '1665 minutes'),
  (gen_random_uuid(), 'room-teacher-school-system--community--teacher-work-style-reform', 'room-teacher-school-system--community--teacher-work-style-reform-t1', 'タケじい', '元校長', 'まず『前例だから』で続いている行事の見直しを。', false, now() - interval '1702 minutes'),
  (gen_random_uuid(), 'room-teacher-school-system--community--teacher-work-style-reform', 'room-teacher-school-system--community--teacher-work-style-reform-t1', 'ごましお', '主幹教諭', '『子どものため』という言葉が、あらゆる業務を断れなくする魔法の言葉になっている。本当に必要かを問い直し、部活や事務作業は外部委託やデジタル化で減らす。教員が倒れては本末転倒だと思います。', false, now() - interval '1739 minutes'),
  (gen_random_uuid(), 'room-teacher-school-system--community--teacher-work-style-reform', 'room-teacher-school-system--community--teacher-work-style-reform-t1', 'うめ子', '高校国語', '保護者対応や調査・報告の多さも相当な負担。ここを国レベルで減らしてほしいです。', false, now() - interval '1776 minutes'),
  (gen_random_uuid(), 'room-teacher-school-system--community--teacher-work-style-reform', 'room-teacher-school-system--community--teacher-work-style-reform-t1', 'ゆずぽん', '3児の母', '先生が疲れていると子どもにしわ寄せがきます。', false, now() - interval '1813 minutes'),
  (gen_random_uuid(), 'room-teacher-school-system--community--school-consolidation', 'room-teacher-school-system--community--school-consolidation-t1', 'タケじい', '元校長', '数の論理だけで決めると、地域から学校という核が消えてしまいます。', false, now() - interval '1850 minutes'),
  (gen_random_uuid(), 'room-teacher-school-system--community--school-consolidation', 'room-teacher-school-system--community--school-consolidation-t1', 'れきお', '社会科', '小規模校は一人ひとりに目が届く良さがある一方、同年代の集団で学ぶ経験や多様な意見に触れる機会は得にくい。通学負担とのトレードオフを、子どもの利益を軸に丁寧に話し合うべきだと思います。', false, now() - interval '1887 minutes'),
  (gen_random_uuid(), 'room-teacher-school-system--community--school-consolidation', 'room-teacher-school-system--community--school-consolidation-t1', 'さくらもち', 'PTA', '統廃合で送迎や見守りの負担が親に増えます。', false, now() - interval '1924 minutes'),
  (gen_random_uuid(), 'room-subject-teaching--community--japanese-language', 'room-subject-teaching--community--japanese-language-t1', 'うめ子', '高校国語', '作文の下書きにAIを使い、推敲の視点を学ぶ使い方は有効だと感じます。', false, now() - interval '1961 minutes'),
  (gen_random_uuid(), 'room-subject-teaching--community--japanese-language', 'room-subject-teaching--community--japanese-language-t1', 'しおりん', '司書', 'AIに要約や添削をさせると、子どもが自分で読む・書く機会を奴いかねない。便利だからこそ、まず自分の言葉で書いてからAIと照らす順序を崩さないこと。読書の量そのものも減らさないでほしいです。', false, now() - interval '1998 minutes'),
  (gen_random_uuid(), 'room-subject-teaching--community--mathematics', 'room-subject-teaching--community--mathematics-t1', 'カエル先生', '中学数学', '計算ドリルの個別最適化は、AIの得意分野です。', false, now() - interval '2035 minutes'),
  (gen_random_uuid(), 'room-subject-teaching--community--mathematics', 'room-subject-teaching--community--mathematics-t1', 'カピバラ', '塾長', '答えだけでなく『なぜその解き方か』を説明させると思考が深まる。逆に途中式をAIに丸投げすると、つまずきが見えなくなる。教員が学習の跡を確認できる使い方を設計したいです。', false, now() - interval '2072 minutes'),
  (gen_random_uuid(), 'room-subject-teaching--community--science', 'room-subject-teaching--community--science-t1', 'モグラ', '中学理科', '危険な実験のシミュレーションなど、AIで安全に試せる場面は多いです。', false, now() - interval '2109 minutes'),
  (gen_random_uuid(), 'room-subject-teaching--community--social-studies', 'room-subject-teaching--community--social-studies-t1', 'れきお', '社会科', '統計データの読み解きや歴史資料の比較に、AIは強力な道具になる。ただ『AIが言ったから正しい』では本末転倒で、出典を確かめ複数の見方を突き合わせる力をセットで育てるのが社会科の役目だと思います。', false, now() - interval '2146 minutes'),
  (gen_random_uuid(), 'room-subject-teaching--community--english-foreign-language', 'room-subject-teaching--community--english-foreign-language-t1', 'ジョニー', '英語科', '発音やスピーキングの練習相手として、AIは恥ずかしがらずに使えるのが利点。', false, now() - interval '2183 minutes'),
  (gen_random_uuid(), 'room-subject-teaching--community--english-foreign-language', 'room-subject-teaching--community--english-foreign-language-t1', 'セナ', '帰国子女', '翻訳AIの精度が上がった今、英語学習の意味づけが問われる。AIは練習の補助に使いつつ、その場で人と心を通わせる体験の価値を伝えたい。道具に頼り切らない設計が大事だと思います。', false, now() - interval '2220 minutes'),
  (gen_random_uuid(), 'room-subject-teaching--community--english-foreign-language', 'room-subject-teaching--community--english-foreign-language-t1', 'タイガ', '高3生', '間違いを気にせず話せる相手ができるのは大きいです。', false, now() - interval '2257 minutes'),
  (gen_random_uuid(), 'room-subject-teaching--community--moral-education', 'room-subject-teaching--community--moral-education-t1', 'しんじ', '道徳研究会', '多様な立場の意見をAIに出させ、議論の材料にするのは面白い試みです。', false, now() - interval '2294 minutes'),
  (gen_random_uuid(), 'room-subject-teaching--community--pe-health', 'room-subject-teaching--community--pe-health-t1', 'まっちょ', '体育会系', '動作をAIで撮って分析すると、苦手な子も上達を実感できます。', false, now() - interval '2331 minutes'),
  (gen_random_uuid(), 'room-subject-teaching--community--music-art', 'room-subject-teaching--community--music-art-t1', 'ドレミ', '音楽', 'AIで作曲や画像生成を体験させると、表現の入り口が広がります。', false, now() - interval '2368 minutes'),
  (gen_random_uuid(), 'room-subject-teaching--community--home-economics-technology', 'room-subject-teaching--community--home-economics-technology-t1', 'おむすび', '家庭科', '献立の栄養計算や被服の型紙づくりなど、AIで効率化できる作業は多いです。', false, now() - interval '2405 minutes'),
  (gen_random_uuid(), 'room-subject-teaching--community--integrated-inquiry-time', 'room-subject-teaching--community--integrated-inquiry-time-t1', 'はるか', '探究コーディネーター', '調べてまとめるだけならAIが代行できる時代。だからこそ総合では『どんな問いを立てるか』『得た答えをどう吟味するか』に重心を移し、AIは情報収集の相棒として位置づけたいです。', false, now() - interval '2442 minutes'),
  (gen_random_uuid(), 'room-subject-teaching--community--integrated-inquiry-time', 'room-subject-teaching--community--integrated-inquiry-time-t1', 'ごましお', '主幹教諭', '教科横断のテーマ設定にAIの助けは大きい。', false, now() - interval '2479 minutes'),
  (gen_random_uuid(), 'room-subject-teaching--community--information-subject', 'room-subject-teaching--community--information-subject-t1', 'テック岡', '情報科', 'プログラミングの初学者がAIに質問しながら学べるのは大きな利点です。', false, now() - interval '2516 minutes'),
  (gen_random_uuid(), 'room-subject-teaching--community--information-subject', 'room-subject-teaching--community--information-subject-t1', '父さん', '元エンジニア', 'ただAIにコードを丸ごと書かせると、なぜ動くかを理解しないまま進んでしまう。生成物を読み解き、直し、説明できる力をセットで育てないと『使えるが分からない』状態に陥ると思います。', false, now() - interval '2553 minutes'),
  (gen_random_uuid(), 'room-subject-teaching--community--information-subject', 'room-subject-teaching--community--information-subject-t1', 'ふじやま', '校務DX担当', '情報モラルも実例で学べる教材になります。', false, now() - interval '2590 minutes'),
  (gen_random_uuid(), 'room-subject-teaching--community--career-guidance', 'room-subject-teaching--community--career-guidance-t1', 'はるか', '探究コーディネーター', '適性や選択肢をAIで可視化するのは有効だが、最後に『どう生きたいか』を考えるのは本人。データが示す『向いている』に流されず、本人の主体性を育てる支援とセットで使いたいです。', false, now() - interval '2627 minutes'),
  (gen_random_uuid(), 'room-subject-teaching--community--career-guidance', 'room-subject-teaching--community--career-guidance-t1', 'うめ子', '高校国語', '偏差値だけでない進路の見せ方ができそうです。', false, now() - interval '2664 minutes'),
  (gen_random_uuid(), 'room-ai-technology--community--digital-textbook', 'room-ai-technology--community--digital-textbook-t2', 'うめ子', '高校国語', '長文をじっくり読む力は、紙のほうが育ちやすいと感じます。', false, now() - interval '2701 minutes'),
  (gen_random_uuid(), 'room-ai-technology--community--digital-textbook', 'room-ai-technology--community--digital-textbook-t2', 'しおりん', '司書', 'スクロールで流し読みになりやすく、深い読解には不利という指摘がある一方、辞書連携や音声読み上げで読みを支えられる面もある。デジタルか紙かではなく、読む目的に応じて使い分ける設計が要ると思います。', false, now() - interval '2738 minutes'),
  (gen_random_uuid(), 'room-ai-technology--community--digital-textbook', 'room-ai-technology--community--digital-textbook-t2', 'まろん', '養護教諭', '目への負担や姿勢の問題も、読解以前に気になるところです。', false, now() - interval '2775 minutes'),
  (gen_random_uuid(), 'room-ai-technology--community--edtech-adoption', 'room-ai-technology--community--edtech-adoption-t2', 'ふじやま', '校務DX担当', 'もはや民間サービスなしに学校は回らない。問題は依存の『質』だと思います。', false, now() - interval '2812 minutes'),
  (gen_random_uuid(), 'room-ai-technology--community--edtech-adoption', 'room-ai-technology--community--edtech-adoption-t2', 'テック岡', '情報科', '特定の企業に深く依存すると、値上げやサービス終了のたびに現場が振り回される。データの持ち出しやすさ、乗り換えのしやすさを契約時に確認しておくことが、長期的なリスク管理になると思います。', false, now() - interval '2849 minutes'),
  (gen_random_uuid(), 'room-ai-technology--community--ai-literacy-moral', 'room-ai-technology--community--ai-literacy-moral-t2', 'れきお', '社会科', '『一次情報にあたる』習慣を低学年から。', false, now() - interval '2886 minutes'),
  (gen_random_uuid(), 'room-ai-technology--community--ai-literacy-moral', 'room-ai-technology--community--ai-literacy-moral-t2', 'テック岡', '情報科', '誤情報や生成AIによる偽画像が湢れる今、見抜く力は必須スキル。ただ『疑え』と教えるだけでは萎縮する。複数の情報源を照らし合わせ、確からしさを自分で確かめる手順を、具体例で繰り返し練習させたいです。', false, now() - interval '2923 minutes'),
  (gen_random_uuid(), 'room-ai-technology--community--ai-literacy-moral', 'room-ai-technology--community--ai-literacy-moral-t2', 'とんかつ', '保護者会長', '家庭でもSNSの情報を鵜呑みにしがち。学校で学んだことを家でも話せるといいです。', false, now() - interval '2960 minutes'),
  (gen_random_uuid(), 'room-ai-technology--community--ai-literacy-moral', 'room-ai-technology--community--ai-literacy-moral-t2', 'コタロー', '大学院生', '『無料』の裏側を考える教材にもなります。', false, now() - interval '2997 minutes'),
  (gen_random_uuid(), 'room-ai-technology--community--personalized-learning', 'room-ai-technology--community--personalized-learning-t2', 'カエル先生', '中学数学', '基礎の反復はアダプティブ教材に任せ、浮いた時間を話し合いに回すのが現実的です。', false, now() - interval '3034 minutes'),
  (gen_random_uuid(), 'room-ai-technology--community--personalized-learning', 'room-ai-technology--community--personalized-learning-t2', 'はるか', '探究コーディネーター', '個別最適と一斉授業は対立しない。一人で進める時間と、みんなで考えを交わす時間を意図的に組み合わせることで、効率と深まりの両方が得られる。教員の授業デザイン力が問われるところだと思います。', false, now() - interval '3071 minutes'),
  (gen_random_uuid(), 'room-evaluation-curriculum--community--inquiry-pbl', 'room-evaluation-curriculum--community--inquiry-pbl-t2', 'はるか', '探究コーディネーター', '成果物の完成度で測ると、見栄えのよい発表が評価されがち。本当に見たいのは『調べる途中で考えが変わった瞬間』を語れるか。思考の跡を評価する視点への転換が必要だと思います。', false, now() - interval '3108 minutes'),
  (gen_random_uuid(), 'room-evaluation-curriculum--community--inquiry-pbl', 'room-evaluation-curriculum--community--inquiry-pbl-t2', 'ごましお', '主幹教諭', 'ルーブリックを生徒と共有すると公正になります。', false, now() - interval '3145 minutes'),
  (gen_random_uuid(), 'room-evaluation-curriculum--community--homework', 'room-evaluation-curriculum--community--homework-t2', 'カエル先生', '中学数学', '丸つけは自動採点に任せ、教員は見取りに集中したい。', false, now() - interval '3182 minutes'),
  (gen_random_uuid(), 'room-evaluation-curriculum--community--homework', 'room-evaluation-curriculum--community--homework-t2', 'ごましお', '主幹教諭', '提出状況の管理や丸つけに時間を取られ、肝心の『つまずきの分析』まで手が回らないのが現場の悩み。AIや相互採点を取り入れ、教員は一人ひとりの理解度を見る時間に振り向けるべきだと思います。', false, now() - interval '3219 minutes'),
  (gen_random_uuid(), 'room-evaluation-curriculum--community--homework', 'room-evaluation-curriculum--community--homework-t2', 'ぱんだ', '小学校教員', '宿題の提出状況から家庭の状況が見える面もあり、悩ましいところです。', false, now() - interval '3256 minutes'),
  (gen_random_uuid(), 'room-evaluation-curriculum--community--course-of-study-revision', 'room-evaluation-curriculum--community--course-of-study-revision-t2', 'タケじい', '元校長', '二項対立で語るより、何を核として残すかを先に決めるべきだと思います。', false, now() - interval '3293 minutes'),
  (gen_random_uuid(), 'room-evaluation-curriculum--community--course-of-study-revision', 'room-evaluation-curriculum--community--course-of-study-revision-t2', 'みずき', '教育ライター', '『詰め込み』批判でゆとりに振れ、学力低下批判でまた詰め込みに戻る——この振り子を繰り返してきた。大事なのは量の調整ではなく、深く学ぶ時間をどう確保するか。現場の声を入れた議論が要ります。', false, now() - interval '3330 minutes'),
  (gen_random_uuid(), 'room-evaluation-curriculum--community--course-of-study-revision', 'room-evaluation-curriculum--community--course-of-study-revision-t2', 'とんかつ', '保護者会長', '範囲が広がり続けて、子の負担が心配です。', false, now() - interval '3367 minutes'),
  (gen_random_uuid(), 'room-evaluation-curriculum--community--non-cognitive-skills', 'room-evaluation-curriculum--community--non-cognitive-skills-t2', 'コタロー', '大学院生', '数値で測ろうとした瞬間、本来の良さが歪む危うさがあります。', false, now() - interval '3404 minutes'),
  (gen_random_uuid(), 'room-evaluation-curriculum--community--non-cognitive-skills', 'room-evaluation-curriculum--community--non-cognitive-skills-t2', 'ごましお', '主幹教諭', '粘り強さや協働性は、テストのように点数化しにくい。だからといって評価しないと指導の手がかりも失う。観察記録やポートフォリオで『変化の過程』を見取る、緩やかな評価が現実解だと思います。', false, now() - interval '3441 minutes'),
  (gen_random_uuid(), 'room-children-rights-discipline--community--school-rules-guidance', 'room-children-rights-discipline--community--school-rules-guidance-t2', 'あおい', '生徒会担当', '『なぜこのルール？』と問い直すことから。', false, now() - interval '3478 minutes'),
  (gen_random_uuid(), 'room-children-rights-discipline--community--school-rules-guidance', 'room-children-rights-discipline--community--school-rules-guidance-t2', 'ごましお', '主幹教諭', '下着の色指定や地毛証明など、合理的な説明ができない決まりは見直すべき。ただ現場には『ルールが多いほうが指導は楽』という本音もある。だからこそ目的を定期的に問い直す仕組みが要ると思います。', false, now() - interval '3515 minutes'),
  (gen_random_uuid(), 'room-children-rights-discipline--community--school-rules-guidance', 'room-children-rights-discipline--community--school-rules-guidance-t2', 'かもめ', '教頭', '安全や他者への配慮に関わる線は残し、それ以外は子どもと一緒に。', false, now() - interval '3552 minutes'),
  (gen_random_uuid(), 'room-children-rights-discipline--community--school-rules-guidance', 'room-children-rights-discipline--community--school-rules-guidance-t2', 'ミント', '中2女子', '中学のとき、意味不明な校則が多かった。', false, now() - interval '3589 minutes'),
  (gen_random_uuid(), 'room-children-rights-discipline--community--bullying-prevention', 'room-children-rights-discipline--community--bullying-prevention-t2', '森のくま', 'スクールカウンセラー', '加害児童の背景には、本人の困りごとが隠れていることが多い。罰するだけでは繰り返す。ただし被害児童の安全確保が最優先で、両者を切り離したうえで加害側にも丁寧に関わる二段構えが要ると思います。', false, now() - interval '3626 minutes'),
  (gen_random_uuid(), 'room-children-rights-discipline--community--bullying-prevention', 'room-children-rights-discipline--community--bullying-prevention-t2', 'まろん', '養護教諭', 'まず被害児童が安心できる環境を。', false, now() - interval '3663 minutes'),
  (gen_random_uuid(), 'room-children-rights-discipline--community--bullying-prevention', 'room-children-rights-discipline--community--bullying-prevention-t2', 'ごましお', '主幹教諭', '担任一人で抱えず、組織と外部機関で対応する体制が不可欠です。', false, now() - interval '3700 minutes'),
  (gen_random_uuid(), 'room-children-rights-discipline--community--school-refusal-support', 'room-children-rights-discipline--community--school-refusal-support-t2', 'ルナ', '不登校経験者', '『復帰』をゴールにすると本人を追い詰めます。', false, now() - interval '3737 minutes'),
  (gen_random_uuid(), 'room-children-rights-discipline--community--school-refusal-support', 'room-children-rights-discipline--community--school-refusal-support-t2', 'ヒナタ', 'フリースクール代表', '目標は学校に戻ることではなく、社会的に自立すること。学校以外の学びの場で力をつける道もある。ただ見守るだけで機会が失われないよう、本人のペースに合わせた選択肢を複数示すことが大事だと思います。', false, now() - interval '3774 minutes'),
  (gen_random_uuid(), 'room-children-rights-discipline--community--school-refusal-support', 'room-children-rights-discipline--community--school-refusal-support-t2', 'ゆずぽん', '3児の母', '親としては『戻ってほしい』と『無理させたくない』で揺れます。', false, now() - interval '3811 minutes'),
  (gen_random_uuid(), 'room-children-rights-discipline--community--smartphone-sns', 'room-children-rights-discipline--community--smartphone-sns-t2', 'ごましお', '主幹教諭', '放課後・校外のトラブルでも、学校に持ち込まれれば対応せざるを得ません。', false, now() - interval '3848 minutes'),
  (gen_random_uuid(), 'room-children-rights-discipline--community--smartphone-sns', 'room-children-rights-discipline--community--smartphone-sns-t2', '森のくま', 'スクールカウンセラー', '『学校外のことだから』と線を引きたくても、子どもの人間関係はつながっている。介入しすぎれば家庭の領分を侵し、放置すれば被害が広がる。家庭や専門機関と連携する前提で関わるしかないと思います。', false, now() - interval '3885 minutes'),
  (gen_random_uuid(), 'room-children-rights-discipline--community--smartphone-sns', 'room-children-rights-discipline--community--smartphone-sns-t2', 'とんかつ', '保護者会長', '保護者としては学校だけに頼れません。', false, now() - interval '3922 minutes'),
  (gen_random_uuid(), 'room-children-rights-discipline--community--smartphone-sns', 'room-children-rights-discipline--community--smartphone-sns-t2', 'ミント', '中2女子', '匿名で相談できる窓口があると助かります。', false, now() - interval '3959 minutes'),
  (gen_random_uuid(), 'room-diversity-inclusion--community--inclusive-special-needs', 'room-diversity-inclusion--community--inclusive-special-needs-t2', 'クローバー', '特別支援', '分けるか混ぜるかの二択ではなく、その子にとって何が学びやすいかが基準。交流の機会を保ちつつ必要な支援は手厚くする柔軟な運用が理想だが、それを支える人員が足りないのが最大の壁です。', false, now() - interval '3996 minutes'),
  (gen_random_uuid(), 'room-diversity-inclusion--community--inclusive-special-needs', 'room-diversity-inclusion--community--inclusive-special-needs-t2', 'くるみ', '放デイ職員', '本人と保護者の希望を一番に。', false, now() - interval '4033 minutes'),
  (gen_random_uuid(), 'room-diversity-inclusion--community--inclusive-special-needs', 'room-diversity-inclusion--community--inclusive-special-needs-t2', 'ぱんだ', '小学校教員', '周りの子にとっても、多様な仲間と過ごす経験は財産になります。', false, now() - interval '4070 minutes'),
  (gen_random_uuid(), 'room-diversity-inclusion--community--multicultural-foreign-roots', 'room-diversity-inclusion--community--multicultural-foreign-roots-t2', 'セナ', '帰国子女', '母語の力は、実は日本語の習得を支える土台にもなります。', false, now() - interval '4107 minutes'),
  (gen_random_uuid(), 'room-diversity-inclusion--community--multicultural-foreign-roots', 'room-diversity-inclusion--community--multicultural-foreign-roots-t2', 'つばさ', 'NPO職員', '日本語指導を優先するあまり母語を切り捨てると、家族との会話やアイデンティティが揺らぐ。母語・母文化を保てる場を地域や保護者と協力して用意することが、結果的にその子の学びと安定につながると思います。', false, now() - interval '4144 minutes'),
  (gen_random_uuid(), 'room-teacher-school-system--community--teacher-work-style-reform', 'room-teacher-school-system--community--teacher-work-style-reform-t2', 'うめ子', '高校国語', '上限を図っても、持ち帰り仕事に変わるだけでは意味がありません。', false, now() - interval '4181 minutes'),
  (gen_random_uuid(), 'room-teacher-school-system--community--teacher-work-style-reform', 'room-teacher-school-system--community--teacher-work-style-reform-t2', 'ごましお', '主幹教諭', '規制に実効性を持たせるには、業務そのものを減らすしかない。勤務時間の記録を厳格にし、削った業務を管理職が明示する。『時間内に終わらない量』を放置したまま上限だけ設けても、現場は苦しくなるだけです。', false, now() - interval '4218 minutes'),
  (gen_random_uuid(), 'room-teacher-school-system--community--teacher-work-style-reform', 'room-teacher-school-system--community--teacher-work-style-reform-t2', 'まっちょ', '体育会系', '部活の地域移行も鍵になります。', false, now() - interval '4255 minutes'),
  (gen_random_uuid(), 'room-teacher-school-system--community--school-consolidation', 'room-teacher-school-system--community--school-consolidation-t2', 'タケじい', '元校長', '学校は選挙の投票所、防災拠点、見守りの場として地域を支えてきた。統廃合で消えると、その機能ごと失われる。教育の効率だけでなく、地域インフラとしての役割も含めて判断すべきだと思います。', false, now() - interval '4292 minutes'),
  (gen_random_uuid(), 'room-teacher-school-system--community--school-consolidation', 'room-teacher-school-system--community--school-consolidation-t2', 'すずめ', '教育委員会', '残すなら維持コストの議論も避けられません。', false, now() - interval '4329 minutes'),
  (gen_random_uuid(), 'room-subject-teaching--community--japanese-language', 'room-subject-teaching--community--japanese-language-t2', '父さん', '元エンジニア', '読めれば十分、書きは最小限でいいのでは。', false, now() - interval '4366 minutes'),
  (gen_random_uuid(), 'room-subject-teaching--community--japanese-language', 'room-subject-teaching--community--japanese-language-t2', 'うめ子', '高校国語', '手で書く過程で字の構造を覚え、読みの力にもつながるという面がある。一方で社会では入力が主流。すべてを手書きで反復させるより、要点を絞って、デジタル入力の指導とバランスを取るのが現実的だと思います。', false, now() - interval '4403 minutes'),
  (gen_random_uuid(), 'room-subject-teaching--community--japanese-language', 'room-subject-teaching--community--japanese-language-t2', 'ぱんだ', '小学校教員', '手書きには集中力や丁寧さを育てる側面もあると感じます。', false, now() - interval '4440 minutes'),
  (gen_random_uuid(), 'room-subject-teaching--community--mathematics', 'room-subject-teaching--community--mathematics-t2', 'カエル先生', '中学数学', '計算手順の理解が先。そのうえで電卓を使うなら有効だと思います。', false, now() - interval '4477 minutes'),
  (gen_random_uuid(), 'room-subject-teaching--community--mathematics', 'room-subject-teaching--community--mathematics-t2', 'カピバラ', '塾長', '電卓やアプリに頼ると計算力が落ちる、という懸念は根強い。でも社会では当たり前に使う道具。基礎の習得段階と、データ処理や応用の段階で、使わせ方を切り替える設計が要ると思います。', false, now() - interval '4514 minutes'),
  (gen_random_uuid(), 'room-subject-teaching--community--science', 'room-subject-teaching--community--science-t2', 'モグラ', '中学理科', '知識の土台がなければ、探究は浅い調べ学習で終わる。逆に暗記だけでは使えない。基礎を効率よく固め、その知識を探究で活かす循環を作るのが、限られた時数の中での現実解だと思います。', false, now() - interval '4551 minutes'),
  (gen_random_uuid(), 'room-subject-teaching--community--science', 'room-subject-teaching--community--science-t2', 'ごましお', '主幹教諭', '両方が要る、というのが現場の実感です。', false, now() - interval '4588 minutes'),
  (gen_random_uuid(), 'room-subject-teaching--community--social-studies', 'room-subject-teaching--community--social-studies-t2', 'れきお', '社会科', '現代の論争的テーマを避けると、社会から切り離された学びになる。ただ扱う以上、教員の政治的中立性をどう保つかが要。結論を出すのではなく、複数の見方を提示し考えさせる訓練が教員側にも必要です。', false, now() - interval '4625 minutes'),
  (gen_random_uuid(), 'room-subject-teaching--community--social-studies', 'room-subject-teaching--community--social-studies-t2', 'とんかつ', '保護者会長', '家庭の価値観との摩擦も生じやすい。', false, now() - interval '4662 minutes'),
  (gen_random_uuid(), 'room-subject-teaching--community--social-studies', 'room-subject-teaching--community--social-studies-t2', 'しんじ', '道徳研究会', '答えのない問いを話し合う経験こそ、これからの社会で要る力です。', false, now() - interval '4699 minutes'),
  (gen_random_uuid(), 'room-subject-teaching--community--english-foreign-language', 'room-subject-teaching--community--english-foreign-language-t2', 'ジョニー', '英語科', '文法・読解の土台がないと、会話も深まらないのが実感です。', false, now() - interval '4736 minutes'),
  (gen_random_uuid(), 'room-subject-teaching--community--english-foreign-language', 'room-subject-teaching--community--english-foreign-language-t2', 'セナ', '帰国子女', '会話偏重で文法を軽視すると、込み入った内容を正確に伝えられなくなる。逆に文法ばかりでは話せない。翻訳AIがある今だからこそ、自分の言葉で伝える楽しさを軸に、両方をつなぐ設計が要ると思います。', false, now() - interval '4773 minutes'),
  (gen_random_uuid(), 'room-subject-teaching--community--moral-education', 'room-subject-teaching--community--moral-education-t2', 'しんじ', '道徳研究会', '『正解』を当てにいく道徳では意味がないと思います。', false, now() - interval '4810 minutes'),
  (gen_random_uuid(), 'room-subject-teaching--community--moral-education', 'room-subject-teaching--community--moral-education-t2', 'うめ子', '高校国語', '評価が入ったことで、子どもが教員の望む答えを書く傾向が強まった。本来は答えのない問いに向き合い、揺れながら考える時間のはず。点数化しにくくても、考えるプロセスそのものを大事にする設計に戻したいです。', false, now() - interval '4847 minutes'),
  (gen_random_uuid(), 'room-subject-teaching--community--pe-health', 'room-subject-teaching--community--pe-health-t2', 'まっちょ', '体育会系', '順位だけ強調すると、運動嫩いを生むだけになりがちです。', false, now() - interval '4884 minutes'),
  (gen_random_uuid(), 'room-subject-teaching--community--pe-health', 'room-subject-teaching--community--pe-health-t2', 'ぽてと', '学童支援員', '競争は意欲を引き出す面もあるが、勝ち負けが固定化すると苦手な子は早々に諸める。順位より『自分の記録がどう伸びたか』を見える化するなど、一人ひとりの達成を軸にする工夫が要ると思います。', false, now() - interval '4921 minutes'),
  (gen_random_uuid(), 'room-subject-teaching--community--pe-health', 'room-subject-teaching--community--pe-health-t2', 'まろん', '養護教諭', '『できた』体験のほうが長く残ります。', false, now() - interval '4958 minutes'),
  (gen_random_uuid(), 'room-subject-teaching--community--music-art', 'room-subject-teaching--community--music-art-t2', 'ドレミ', '音楽', '基礎技能がないと自由な表現も広がらない一方、技術練習ばかりでは『やらされ』になり、表現する喜びが薄れる。まず楽しいと感じる入り口を作り、必要な技能はその中で身につける順序が大事だと思います。', false, now() - interval '4995 minutes'),
  (gen_random_uuid(), 'room-subject-teaching--community--home-economics-technology', 'room-subject-teaching--community--home-economics-technology-t2', 'おむすび', '家庭科', '調理や金銭管理など、生きる力は学校でも扱う価値があります。', false, now() - interval '5032 minutes'),
  (gen_random_uuid(), 'room-subject-teaching--community--home-economics-technology', 'room-subject-teaching--community--home-economics-technology-t2', 'つばさ', 'NPO職員', '本来は家庭で身につくはずのことが学校に求められる背景には、家庭の余裕のなさがある。学校が全部抱えるのは無理だが、最低限の生活スキルを学ぶ場を保障することは、格差を埋める意味で意義があると思います。', false, now() - interval '5069 minutes'),
  (gen_random_uuid(), 'room-subject-teaching--community--integrated-inquiry-time', 'room-subject-teaching--community--integrated-inquiry-time-t2', 'ごましお', '主幹教諭', '教科の壁を越えた学びは理想だが、時間割や教員配置の制約で『やりにくい』のが現実。総合の時間を軸に、各教科の知識を持ち寄るテーマを設定すると、現場でも回せる横断設計になると思います。', false, now() - interval '5106 minutes'),
  (gen_random_uuid(), 'room-subject-teaching--community--information-subject', 'room-subject-teaching--community--information-subject-t2', 'テック岡', '情報科', '技術だけ教えても、使い方の倫理が伴わなければ危うい。両輪です。', false, now() - interval '5143 minutes'),
  (gen_random_uuid(), 'room-subject-teaching--community--information-subject', 'room-subject-teaching--community--information-subject-t2', '父さん', '元エンジニア', 'プログラミングなどの技術力は将来の選択肢を広げるが、個人情報や著作権、誹謗中傷への意識が抜けると、技術が凶器になりかねない。モラルと技術は切り離さず、実例を通して同時に学ばせたいです。', false, now() - interval '5180 minutes'),
  (gen_random_uuid(), 'room-subject-teaching--community--career-guidance', 'room-subject-teaching--community--career-guidance-t2', 'はるか', '探究コーディネーター', '偏差値は分かりやすい指標だが、それだけで進路を決めると『入れる学校』に流される。本人が何に夢中になれるかを軸に、多様な進路情報を示すことが、変化の時代の進路指導だと思います。', false, now() - interval '5217 minutes'),
  (gen_random_uuid(), 'room-subject-teaching--community--career-guidance', 'room-subject-teaching--community--career-guidance-t2', 'ゆずぽん', '3児の母', '数値以外の物差しを親子で持ちたい。', false, now() - interval '5254 minutes'),
  (gen_random_uuid(), 'room-subject-teaching--community--career-guidance', 'room-subject-teaching--community--career-guidance-t2', 'うめ子', '高校国語', '脱却したくても、入試制度が偏差値前提だと現場も動きにくい。', false, now() - interval '5291 minutes'),
  (gen_random_uuid(), 'room-subject-teaching--community--career-guidance', 'room-subject-teaching--community--career-guidance-t2', 'とんかつ', '保護者会長', '本人の『好き』を一番に考えたい。', false, now() - interval '5328 minutes'),
  (gen_random_uuid(), 'room-ai-technology--community--digital-textbook', 'room-ai-technology--community--digital-textbook-t3', 'うめ子', '高校国語', '二者択一でなく、目的で使い分けるのが現実的です。', false, now() - interval '5365 minutes'),
  (gen_random_uuid(), 'room-ai-technology--community--digital-textbook', 'room-ai-technology--community--digital-textbook-t3', 'ふじやま', '校務DX担当', '集中して読む場面は紙、検索や動画連動・共同編集はデジタル、と場面で選ぶのが自然。ただ使い分けの基準を現場の裁量に丸投げすると中途半端になりがちなので、学校として一定の方針を示してほしいです。', false, now() - interval '5402 minutes'),
  (gen_random_uuid(), 'room-ai-technology--community--digital-textbook', 'room-ai-technology--community--digital-textbook-t3', 'ゆずぽん', '3児の母', '家でも学校でもデジタルだと、紙の本をめくる経験そのものが減ります。', false, now() - interval '5439 minutes'),
  (gen_random_uuid(), 'room-ai-technology--community--edtech-adoption', 'room-ai-technology--community--edtech-adoption-t3', 'テック岡', '情報科', '無料サービスは『データが商品』のことが多い。何と引き換えかを見て使いたい。', false, now() - interval '5476 minutes'),
  (gen_random_uuid(), 'room-ai-technology--community--edtech-adoption', 'room-ai-technology--community--edtech-adoption-t3', 'ふじやま', '校務DX担当', '現場が無料だからと個別に導入すると、学校全体でデータ管理がバラバラになる。利用規約のチェック体制を整え、どのサービスを使うか組織で判断する仕組みが要る。安さの裏のリスクを見ぬく目が大事です。', false, now() - interval '5513 minutes'),
  (gen_random_uuid(), 'room-ai-technology--community--ai-literacy-moral', 'room-ai-technology--community--ai-literacy-moral-t3', '森のくま', 'スクールカウンセラー', '情報モラルは学校か家庭かではなく、両者が同じ言葉で語ることが大事。学校が見取り図を示し、家庭が日常で実践する分担が現実的。トラブルは家庭で起きて学校に持ち込まれることが多く、連携しないと実効性がありません。', false, now() - interval '5550 minutes'),
  (gen_random_uuid(), 'room-ai-technology--community--ai-literacy-moral', 'room-ai-technology--community--ai-literacy-moral-t3', 'ごましお', '主幹教諭', '家庭に丸投げしても、詳しくない保護者は多い。', false, now() - interval '5587 minutes'),
  (gen_random_uuid(), 'room-ai-technology--community--ai-literacy-moral', 'room-ai-technology--community--ai-literacy-moral-t3', 'ゆずぽん', '3児の母', '子どものほうが親よりデバイスに詳しい現状では、学校の専門的な支援が要ります。', false, now() - interval '5624 minutes'),
  (gen_random_uuid(), 'room-ai-technology--community--personalized-learning', 'room-ai-technology--community--personalized-learning-t3', 'コタロー', '大学院生', '『点数が上がる』だけの最適化に陥らないか。誰のための最適化かが問われます。', false, now() - interval '5661 minutes'),
  (gen_random_uuid(), 'room-ai-technology--community--personalized-learning', 'room-ai-technology--community--personalized-learning-t3', 'テック岡', '情報科', '最適化のアルゴリズムがブラックボックスのままだと、なぜその問題が出たのか説明できない。透明性の確保が必須で、何より子ども本人が『どう学びたいか』を言える状態でないと、誰かの都合の最適化になってしまいます。', false, now() - interval '5698 minutes'),
  (gen_random_uuid(), 'room-evaluation-curriculum--community--inquiry-pbl', 'room-evaluation-curriculum--community--inquiry-pbl-t3', 'はるか', '探究コーディネーター', '両者は対立しません。むしろ補い合う関係です。', false, now() - interval '5735 minutes'),
  (gen_random_uuid(), 'room-evaluation-curriculum--community--inquiry-pbl', 'room-evaluation-curriculum--community--inquiry-pbl-t3', 'カエル先生', '中学数学', '教科で身につけた知識を探究で使い、探究で生まれた問いを教科で深める循環が理想。ただ限られた授業時数で両方を成立させるのは至難で、基礎をデジタルで効率化し、浮いた時間を探究に回す工夫が要ります。', false, now() - interval '5772 minutes'),
  (gen_random_uuid(), 'room-evaluation-curriculum--community--inquiry-pbl', 'room-evaluation-curriculum--community--inquiry-pbl-t3', 'とんかつ', '保護者会長', '受験を控えると、探究に時間を割いて大丈夫か不安になります。', false, now() - interval '5809 minutes'),
  (gen_random_uuid(), 'room-evaluation-curriculum--community--homework', 'room-evaluation-curriculum--community--homework-t3', 'つばさ', 'NPO職員', '宿題が家庭のサポート力を前提にした瞬間、格差を広げる。共働きやひとり親では見てあげる余裕がないのが現実で、『家でやる前提』の設計を見直し、学校や地域でやれる場を充実させるべきだと思います。', false, now() - interval '5846 minutes'),
  (gen_random_uuid(), 'room-evaluation-curriculum--community--homework', 'room-evaluation-curriculum--community--homework-t3', 'ぱんだ', '小学校教員', '学校内で完結する学習時間を確保したい。', false, now() - interval '5883 minutes'),
  (gen_random_uuid(), 'room-evaluation-curriculum--community--homework', 'room-evaluation-curriculum--community--homework-t3', 'くるみ', '放デイ職員', '放課後の学習支援を充実させれば、格差はかなり緩和できます。', false, now() - interval '5920 minutes'),
  (gen_random_uuid(), 'room-evaluation-curriculum--community--homework', 'room-evaluation-curriculum--community--homework-t3', 'あられ', '小1ママ', '共働きだと見る時間がないのが現実です。', false, now() - interval '5957 minutes'),
  (gen_random_uuid(), 'room-evaluation-curriculum--community--course-of-study-revision', 'room-evaluation-curriculum--community--course-of-study-revision-t3', 'タケじい', '元校長', '『増やす』議論より『何を処理できるか』を先に決めるべきです。', false, now() - interval '5994 minutes'),
  (gen_random_uuid(), 'room-evaluation-curriculum--community--course-of-study-revision', 'room-evaluation-curriculum--community--course-of-study-revision-t3', 'ごましお', '主幹教諭', '情報・防災・金融・言語と必要なものは増える一方。だが現場のキャパシティを超えた詰め込みはもう限界で、増やすなら授業時数か教員数も同時に議論しないと、しわ寄せが現場に来るだけです。', false, now() - interval '6031 minutes'),
  (gen_random_uuid(), 'room-evaluation-curriculum--community--non-cognitive-skills', 'room-evaluation-curriculum--community--non-cognitive-skills-t3', 'コタロー', '大学院生', '優劣ではなく車の両輪。優先順位の発想自体が学びを狭めます。', false, now() - interval '6068 minutes'),
  (gen_random_uuid(), 'room-evaluation-curriculum--community--non-cognitive-skills', 'room-evaluation-curriculum--community--non-cognitive-skills-t3', 'ごましお', '主幹教諭', '現場で限られた時間を配分する以上、どちらに重きを置くかの選択は避けられない。結局テストで測れる認知が優先されがちだが、社会に出てから効いてくるのは非認知の力。長い目で見る視点を忘れたくないです。', false, now() - interval '6105 minutes'),
  (gen_random_uuid(), 'room-children-rights-discipline--community--school-rules-guidance', 'room-children-rights-discipline--community--school-rules-guidance-t3', 'れきお', '社会科', '『安全と学習環境を守るため』にあるはず。昔からあるだけの決まりは外していい。', false, now() - interval '6142 minutes'),
  (gen_random_uuid(), 'room-children-rights-discipline--community--school-rules-guidance', 'room-children-rights-discipline--community--school-rules-guidance-t3', 'あおい', '生徒会担当', '『何のために』を生徒と一緒に考えることそのものが、生きた主権者教育になる。守らせる対象ではなく考える教材として扱えば、理不尽な校則は自然と整理される。理由を説明できるかを基準にすればいいと思います。', false, now() - interval '6179 minutes'),
  (gen_random_uuid(), 'room-children-rights-discipline--community--school-rules-guidance', 'room-children-rights-discipline--community--school-rules-guidance-t3', 'ごましお', '主幹教諭', 'ルールが多いほうが指導は楽、という本音もあります。', false, now() - interval '6216 minutes'),
  (gen_random_uuid(), 'room-children-rights-discipline--community--school-rules-guidance', 'room-children-rights-discipline--community--school-rules-guidance-t3', 'とんかつ', '保護者会長', '理由を説明できる校則なら納得できます。', false, now() - interval '6253 minutes'),
  (gen_random_uuid(), 'room-children-rights-discipline--community--bullying-prevention', 'room-children-rights-discipline--community--bullying-prevention-t3', '森のくま', 'スクールカウンセラー', '『言い出せない子』の声を拾う点で有効。匿名で通報できると、告げ口と思われるのを恐れる子の助けになる。ただ『アプリさえ入れれば安心』にならないよう、受け皿となる人の体制が伴うことが前提だと思います。', false, now() - interval '6290 minutes'),
  (gen_random_uuid(), 'room-children-rights-discipline--community--bullying-prevention', 'room-children-rights-discipline--community--bullying-prevention-t3', 'テック岡', '情報科', '誤検知や、監視と保護の境界が難しい。', false, now() - interval '6327 minutes'),
  (gen_random_uuid(), 'room-children-rights-discipline--community--bullying-prevention', 'room-children-rights-discipline--community--bullying-prevention-t3', 'まろん', '養護教諭', '早期発見は安心だが、人のフォローがないと意味がありません。', false, now() - interval '6364 minutes'),
  (gen_random_uuid(), 'room-children-rights-discipline--community--school-refusal-support', 'room-children-rights-discipline--community--school-refusal-support-t3', 'ルナ', '不登校経験者', '『問題」と見る視線そのものが子を追い詰めます。', false, now() - interval '6401 minutes'),
  (gen_random_uuid(), 'room-children-rights-discipline--community--school-refusal-support', 'room-children-rights-discipline--community--school-refusal-support-t3', 'ぱんだ', '小学校教員', '『学校が合わなかった』という中立的な見方も必要。一方で学びの機会が長期間失われるのを問題ないと言い切るのも危うい。問題視しないことと放置しないことは両立するので、安心できる場を複数用意して学びを繋ぎたいです。', false, now() - interval '6438 minutes'),
  (gen_random_uuid(), 'room-children-rights-discipline--community--school-refusal-support', 'room-children-rights-discipline--community--school-refusal-support-t3', 'つばさ', 'NPO職員', '見守りつつ学びを保障するバランスが難しいところです。', false, now() - interval '6475 minutes'),
  (gen_random_uuid(), 'room-children-rights-discipline--community--school-refusal-support', 'room-children-rights-discipline--community--school-refusal-support-t3', 'ゆずぽん', '3児の母', '見方を変えるだけで親子の心が軽くなります。', false, now() - interval '6512 minutes'),
  (gen_random_uuid(), 'room-children-rights-discipline--community--smartphone-sns', 'room-children-rights-discipline--community--smartphone-sns-t3', '森のくま', 'スクールカウンセラー', '学校・家庭・本人の三者が協力するしかないテーマだと思います。', false, now() - interval '6549 minutes'),
  (gen_random_uuid(), 'room-children-rights-discipline--community--smartphone-sns', 'room-children-rights-discipline--community--smartphone-sns-t3', 'タイガ', '高3生', '本人が『自分でコントロールする力』を身につけるのがゴール。ただ依存性の高い設計のSNSやゲームに子ども一人で抵抗するのは酷で、大人と仕組みのサポートが要る。誰かに丸投げした瞬間にうまくいかなくなります。', false, now() - interval '6586 minutes'),
  (gen_random_uuid(), 'room-children-rights-discipline--community--smartphone-sns', 'room-children-rights-discipline--community--smartphone-sns-t3', 'あられ', '小1ママ', '親世代はスマホがなく、教え方が分からないです。', false, now() - interval '6623 minutes'),
  (gen_random_uuid(), 'room-diversity-inclusion--community--inclusive-special-needs', 'room-diversity-inclusion--community--inclusive-special-needs-t3', 'クローバー', '特別支援', '理念を支えるのは人員。介助員や支援員の配置を拡充しない限り、現場の負担だけが増す。人員確保には財源が要るので、どこから予算を持ってくるかまで踏み込まないと、理念を語るだけで現場が疲弊します。', false, now() - interval '6660 minutes'),
  (gen_random_uuid(), 'room-diversity-inclusion--community--inclusive-special-needs', 'room-diversity-inclusion--community--inclusive-special-needs-t3', 'タケじい', '元校長', '地域のボランティアや学生サポーターの活用も。', false, now() - interval '6697 minutes'),
  (gen_random_uuid(), 'room-diversity-inclusion--community--inclusive-special-needs', 'room-diversity-inclusion--community--inclusive-special-needs-t3', 'くるみ', '放デイ職員', '人手不足で『インクルーシブ』が名ばかりになっている例も見てきました。', false, now() - interval '6734 minutes'),
  (gen_random_uuid(), 'room-diversity-inclusion--community--multicultural-foreign-roots', 'room-diversity-inclusion--community--multicultural-foreign-roots-t3', 'ふじやま', '校務DX担当', '翻訳AIや多言語教材で、少人数の言語にも現実的に対応できる時代です。', false, now() - interval '6771 minutes'),
  (gen_random_uuid(), 'room-diversity-inclusion--community--multicultural-foreign-roots', 'room-diversity-inclusion--community--multicultural-foreign-roots-t3', '森のくま', 'スクールカウンセラー', 'ツールで日常会話は回っても、心のケアや進路相談など微妙なニュアンスは人間が必要。どこまでをAIに任せるかは地域により、集住地域は人の配置、点在地域はAIを、とリソースに応じて柔軟に考えるのが現実的だと思います。', false, now() - interval '6808 minutes'),
  (gen_random_uuid(), 'room-teacher-school-system--community--teacher-work-style-reform', 'room-teacher-school-system--community--teacher-work-style-reform-t3', 'タケじい', '元校長', '『子どものため』が、業務を断れなくする魔法の言葉に。', false, now() - interval '6845 minutes'),
  (gen_random_uuid(), 'room-teacher-school-system--community--teacher-work-style-reform', 'room-teacher-school-system--community--teacher-work-style-reform-t3', 'ごましお', '主幹教諭', '動機が善意なだけに断りにくいが、教員が倒れては本末転倒。『これは本当に子どものためか、教員の自己満足か』を問う仕組みが要る。前例があるから、保護者が言うかも、で業務が増える構造を管理職が断ち切るべきです。', false, now() - interval '6882 minutes'),
  (gen_random_uuid(), 'room-teacher-school-system--community--teacher-work-style-reform', 'room-teacher-school-system--community--teacher-work-style-reform-t3', 'ゆずぽん', '3児の母', '先生が疲弊していると、結局子どもにしわ寄せがくると感じます。', false, now() - interval '6919 minutes'),
  (gen_random_uuid(), 'room-teacher-school-system--community--teacher-work-style-reform', 'room-teacher-school-system--community--teacher-work-style-reform-t3', 'かもめ', '教頭', '『やめる』判断こそ評価したい。', false, now() - interval '6956 minutes'),
  (gen_random_uuid(), 'room-teacher-school-system--community--school-consolidation', 'room-teacher-school-system--community--school-consolidation-t3', 'ゆずぽん', '3児の母', '通学負担の増加は、特に低学年や体力のない子に深刻。スクールバスの運行コストも含めて長期的な負担を試算すべき。送迎や見守り当番など保護者の負担も増えるので、家庭への影響も見てほしいです。', false, now() - interval '6993 minutes'),
  (gen_random_uuid(), 'room-teacher-school-system--community--school-consolidation', 'room-teacher-school-system--community--school-consolidation-t3', 'ノリック', 'ICT支援員', '移動時間をオンライン朝学に活かす例も。', false, now() - interval '7030 minutes'),
  (gen_random_uuid(), 'room-subject-teaching--community--japanese-language', 'room-subject-teaching--community--japanese-language-t3', 'うめ子', '高校国語', 'パフォーマンス評価は不可欠だが、教員の負担が大きいのが課題です。', false, now() - interval '7067 minutes'),
  (gen_random_uuid(), 'room-subject-teaching--community--japanese-language', 'room-subject-teaching--community--japanese-language-t3', 'ごましお', '主幹教諭', 'ペーパーテストで測れない力だからこそ、プレゼンや討論の機会を日常的に作るべき。評価の主観性はルーブリックの整備や複数の教員で見る仕組みで担保し、AIによる下書き評価の補助も現実解になります。', false, now() - interval '7104 minutes'),
  (gen_random_uuid(), 'room-subject-teaching--community--mathematics', 'room-subject-teaching--community--mathematics-t3', 'カエル先生', '中学数学', '『なぜ数学を』には、論理的に考える力や物事を抽象化する力を養うため、と答えています。計算そのものは手段にすぎない。ただ学んでいる最中の生徒には届きにくいので、実生活や他教科とのつながりを見せると納得してくれます。', false, now() - interval '7141 minutes'),
  (gen_random_uuid(), 'room-subject-teaching--community--mathematics', 'room-subject-teaching--community--mathematics-t3', 'タイガ', '高3生', '統計やデータ分析など、使われる場面を見せたい。', false, now() - interval '7178 minutes'),
  (gen_random_uuid(), 'room-subject-teaching--community--mathematics', 'room-subject-teaching--community--mathematics-t3', 'ゆずぽん', '3児の母', '親も『なんで勉強するの』と聞かれて答えに詰まります。', false, now() - interval '7215 minutes'),
  (gen_random_uuid(), 'room-subject-teaching--community--mathematics', 'room-subject-teaching--community--mathematics-t3', 'コタロー', '大学院生', '抽象論だけでは生徒は動きません。', false, now() - interval '7252 minutes'),
  (gen_random_uuid(), 'room-subject-teaching--community--science', 'room-subject-teaching--community--science-t3', 'モグラ', '中学理科', '『不思議』を体験する前に試験勉強になってしまうのが背景にあります。', false, now() - interval '7289 minutes'),
  (gen_random_uuid(), 'room-subject-teaching--community--science', 'room-subject-teaching--community--science-t3', 'コタロー', '大学院生', '実験の準備・片付けに追われ、本来の『なぜ？』を考える時間が取れないのが現場の悩み。身近な現象や最新の科学トピックと結びつけると生徒の目の輝きが変わるので、教科書の順番だけでなく『今」と繋げる工夫が鍵です。', false, now() - interval '7326 minutes'),
  (gen_random_uuid(), 'room-subject-teaching--community--social-studies', 'room-subject-teaching--community--social-studies-t3', 'れきお', '社会科', '『投票の仕方』だけでなく、身近な課題を自分事として考え、合意形成する経験が本質。校則見直しなど身近な題材が最適で、結論を出すより複数の見方を扱う訓練が、教員側にも生徒側にも要ると思います。', false, now() - interval '7363 minutes'),
  (gen_random_uuid(), 'room-subject-teaching--community--social-studies', 'room-subject-teaching--community--social-studies-t3', 'あおい', '生徒会担当', '小中から『自分たちで決める』経験を。', false, now() - interval '7400 minutes'),
  (gen_random_uuid(), 'room-subject-teaching--community--english-foreign-language', 'room-subject-teaching--community--english-foreign-language-t3', 'ジョニー', '英語科', '翻訳AIがある今、英語を学ぶ意味は『その場で人と心を通わせる体験』にあります。', false, now() - interval '7437 minutes'),
  (gen_random_uuid(), 'room-subject-teaching--community--english-foreign-language', 'room-subject-teaching--community--english-foreign-language-t3', 'セナ', '帰国子女', '翻訳AIの精度が上がり、『実用』だけを理由にしにくくなった。だが翻訳に頼ると微妙なニュアンスやその場のユーモアが伝わらない。言語を通した異文化理解など、新しい動機づけと、自分の言葉で話せる豊かさを伝えたいです。', false, now() - interval '7474 minutes'),
  (gen_random_uuid(), 'room-subject-teaching--community--english-foreign-language', 'room-subject-teaching--community--english-foreign-language-t3', 'とんかつ', '保護者会長', '将来海外で働く可能性も考えたいです。', false, now() - interval '7511 minutes'),
  (gen_random_uuid(), 'room-subject-teaching--community--moral-education', 'room-subject-teaching--community--moral-education-t3', 'コタロー', '大学院生', '『どの価値が正しいか』ではなく『違う価値観の人とどう協力するか』を扱うべき。結論を出さない議論の価値を伝えたい。多様性を講じるなら、教員自身の価値観を押し付けない姿勢が不可欠だと思います。', false, now() - interval '7548 minutes'),
  (gen_random_uuid(), 'room-subject-teaching--community--moral-education', 'room-subject-teaching--community--moral-education-t3', 'セナ', '帰国子女', '『普通』を前提にした道徳は誰かを傷つけます。', false, now() - interval '7585 minutes'),
  (gen_random_uuid(), 'room-subject-teaching--community--pe-health', 'room-subject-teaching--community--pe-health-t3', 'まろん', '養護教諭', '『踏み込まない』ことでリスクが高まる領域。正確な知識を発達段階に応じて届けることが、結局は子どもを守る。ネットに誤った・過激な情報が溢れる今だからこそ、学校が安心できる情報源になってほしいです。', false, now() - interval '7622 minutes'),
  (gen_random_uuid(), 'room-subject-teaching--community--pe-health', 'room-subject-teaching--community--pe-health-t3', 'とんかつ', '保護者会長', '家庭の価値観や宗教的背景との摩擦も生じます。', false, now() - interval '7659 minutes'),
  (gen_random_uuid(), 'room-subject-teaching--community--pe-health', 'room-subject-teaching--community--pe-health-t3', 'かもめ', '教頭', '保護者との事前の丁寧な説明と合意が不可欠だと思います。', false, now() - interval '7696 minutes'),
  (gen_random_uuid(), 'room-subject-teaching--community--music-art', 'room-subject-teaching--community--music-art-t3', 'あおい', '美術部顧問', '効率や数値で表せないものを軽んじる風潮の表れだと感じます。', false, now() - interval '7733 minutes'),
  (gen_random_uuid(), 'room-subject-teaching--community--music-art', 'room-subject-teaching--community--music-art-t3', 'ドレミ', '音楽', '感性や表現力は子どもの人生を豊かにする根幹。削減に反対するなら他の何を減らすのかを語らないと議論が進まないのが辛いが、部活動や地域の文化活動と連携させれば限られた時数を補うこともできると思います。', false, now() - interval '7770 minutes'),
  (gen_random_uuid(), 'room-subject-teaching--community--home-economics-technology', 'room-subject-teaching--community--home-economics-technology-t3', 'テック岡', '情報科', 'ものづくりとプログラミングは本来相性がいい。センサーやロボットを動かす中で、技術とプログラミングが自然につながる。ただ指導できる教員と設備の差が学力差にならないよう、体制整備とセットで進めたいです。', false, now() - interval '7807 minutes'),
  (gen_random_uuid(), 'room-subject-teaching--community--integrated-inquiry-time', 'room-subject-teaching--community--integrated-inquiry-time-t3', 'はるか', '探究コーディネーター', '『調べてまとめる』だけならもうAIが代行できる時代。身につけるべきは『どんな問いを立てるか』と『得た答えをどう吟味するか』。成果物の完成度ではなく、思考の跡や試行錯誤のプロセスを評価する視点への転換が必要です。', false, now() - interval '7844 minutes'),
  (gen_random_uuid(), 'room-subject-teaching--community--information-subject', 'room-subject-teaching--community--information-subject-t3', 'テック岡', '情報科', '入試科目化された『情報』は、データを読み解き活用する力としてすべての分野で生きる。大学での学びや仕事に直結するため自然な流れだが、暗記中心にならずプログラミング的思考を評価する良問作りが生命線だと思います。', false, now() - interval '7881 minutes'),
  (gen_random_uuid(), 'room-subject-teaching--community--information-subject', 'room-subject-teaching--community--information-subject-t3', 'すずめ', '教育委員会', '指導できる教員と設備の差が懸念です。', false, now() - interval '7918 minutes'),
  (gen_random_uuid(), 'room-subject-teaching--community--information-subject', 'room-subject-teaching--community--information-subject-t3', 'とんかつ', '保護者会長', '受験負担がまた増えるのかと不安になります。', false, now() - interval '7955 minutes'),
  (gen_random_uuid(), 'room-subject-teaching--community--career-guidance', 'room-subject-teaching--community--career-guidance-t3', 'はるか', '探究コーディネーター', '特定の職業をゴールにするより『学び続ける力』や『変化に適応する力』を基軸にしたい。AIやデータで適性や選択肢を可視化するのは有効だが、最後に『どう生きたいか』を考えるのは本人。その主体性を育てる支援が大事です。', false, now() - interval '7992 minutes'),
  (gen_random_uuid(), 'room-subject-teaching--community--career-guidance', 'room-subject-teaching--community--career-guidance-t3', 'コタロー', '大学院生', '生徒や保護者は具体的な職業像を知りたがります。', false, now() - interval '8029 minutes'),
  (gen_random_uuid(), 'room-subject-teaching--community--career-guidance', 'room-subject-teaching--community--career-guidance-t3', 'ゆずぽん', '3児の母', '偏差値より『夢中になれること』を軸にしたいです。', false, now() - interval '8066 minutes');

-- 念のため: 残存する NULL topic_id を本文一致で論点へ紐づけ
UPDATE public.forum_posts AS p
SET topic_id = m.topic_id
FROM (VALUES
  ('room-ai-technology--community--digital-textbook', '全面移行には反対です。紙をめくって読む集中力も大事に育てたい。', 'room-ai-technology--community--digital-textbook-t1'),
  ('room-ai-technology--community--digital-textbook', 'デジタルは検索や動画連動、書き込みの共有など利点が多い一方、長時間の画面で目が疲れる、通信トラブルで授業が止まるといった不安も根強い。まずは教科や場面を限った段階的な併用から始めるのが現実的だと思います。', 'room-ai-technology--community--digital-textbook-t1'),
  ('room-ai-technology--community--digital-textbook', '紙とデジタルでは記憶の定着の仕方が違うという研究もあります。使い分ける前提で議論したいです。', 'room-ai-technology--community--digital-textbook-t1'),
  ('room-ai-technology--community--digital-textbook', '家庭のWi-Fi環境に差があるので、全面移行は格差を広げないか心配です。', 'room-ai-technology--community--digital-textbook-t1'),
  ('room-ai-technology--community--edtech-adoption', '価格や知名度ではなく、子どものデータがどう守られるかを最優先に選ぶべきです。', 'room-ai-technology--community--edtech-adoption-t1'),
  ('room-ai-technology--community--edtech-adoption', '現場が使いこなせるかが一番の問題。', 'room-ai-technology--community--edtech-adoption-t1'),
  ('room-ai-technology--community--ai-literacy-moral', '低学年からでも『鵜呑みにしない』姿勢は教えられます。', 'room-ai-technology--community--ai-literacy-moral-t1'),
  ('room-ai-technology--community--ai-literacy-moral', '年齢で線を引くより、デバイスに触れ始めた時点が開始点だと思います。幼くてもAIの答えが必ずしも正しくないこと、個人情報を打ち込まないことは、具体例で繰り返し伝えれば十分に伝わります。', 'room-ai-technology--community--ai-literacy-moral-t1'),
  ('room-ai-technology--community--ai-literacy-moral', '家庭でスマホを使い始める年齢が下がっている以上、学校の指導が追いついていないのが実情です。', 'room-ai-technology--community--ai-literacy-moral-t1'),
  ('room-ai-technology--community--personalized-learning', '一人ひとりに合った進度で学べるのは大きな利点。つまずきを早く見つけられます。', 'room-ai-technology--community--personalized-learning-t1'),
  ('room-ai-technology--community--personalized-learning', 'ただ画面に向かう時間が増えると、友達と話し合いながら学ぶ機会が減る。最適化は道具として使い、人と関わる学びと組み合わせてこそ豊かになる。孤立させるかどうかは教員の設計次第だと思います。', 'room-ai-technology--community--personalized-learning-t1'),
  ('room-ai-technology--community--personalized-learning', '『最適』を誰が決めるのかが気になります。', 'room-ai-technology--community--personalized-learning-t1'),
  ('room-evaluation-curriculum--community--inquiry-pbl', 'テストの点だけ見れば効果はすぐ表れにくい。でも『自分で問いを立てて調べる』経験は、長い目で学ぶ意欲や思考力につながります。何を学力と呼ぶかの議論が先です。', 'room-evaluation-curriculum--community--inquiry-pbl-t1'),
  ('room-evaluation-curriculum--community--inquiry-pbl', 'やりっぱなしにせず、振り返りまでが探究です。', 'room-evaluation-curriculum--community--inquiry-pbl-t1'),
  ('room-evaluation-curriculum--community--inquiry-pbl', '受験を控えると、探究に時間を割く余裕があるのか不安になるのが親の本音です。', 'room-evaluation-curriculum--community--inquiry-pbl-t1'),
  ('room-evaluation-curriculum--community--homework', '一律の宿題は、もう時代に合わないと思います。', 'room-evaluation-curriculum--community--homework-t1'),
  ('room-evaluation-curriculum--community--homework', '家庭のサポート力に差がある以上、宿題前提の設計は格差を広げます。学校内で完結させたい。', 'room-evaluation-curriculum--community--homework-t1'),
  ('room-evaluation-curriculum--community--homework', '全部なくすのではなく、子どもが内容を選べる『自学』にすると、やらされ感が減って力もつく。丸つけや管理を全部教員が背負わず、AIや相互チェックを取り入れる工夫も要ります。', 'room-evaluation-curriculum--community--homework-t1'),
  ('room-evaluation-curriculum--community--homework', '共働きだと、見てあげる時間がないのが現実です。', 'room-evaluation-curriculum--community--homework-t1'),
  ('room-evaluation-curriculum--community--course-of-study-revision', '細かく決まっているからこそ、どの学校でも一定の質が保たれる面もあります。', 'room-evaluation-curriculum--community--course-of-study-revision-t1'),
  ('room-evaluation-curriculum--community--course-of-study-revision', '内容が多すぎて『こなす』だけで精一杯になり、目の前の子に合わせて工夫する余白がない。最低限の核を示したうえで、あとは現場に委ねるくらいでちょうどいいと感じます。', 'room-evaluation-curriculum--community--course-of-study-revision-t1'),
  ('room-evaluation-curriculum--community--course-of-study-revision', '自由度より、まず時数と内容のバランスを見直してほしいです。', 'room-evaluation-curriculum--community--course-of-study-revision-t1'),
  ('room-evaluation-curriculum--community--course-of-study-revision', '国の方針があるから保護者も安心できる面はある。自由と標準の線引きが難しいですね。', 'room-evaluation-curriculum--community--course-of-study-revision-t1'),
  ('room-evaluation-curriculum--community--non-cognitive-skills', '数値化しにくいだけで、毎日の関わりの中で確かに育っています。', 'room-evaluation-curriculum--community--non-cognitive-skills-t1'),
  ('room-evaluation-curriculum--community--non-cognitive-skills', '協働や粘り強さは、行事や日々のトラブル対応の中で自然に育つもの。ただ『育てている』と意識せず流してしまうと、子どもによって経験に差が出る。意図的に場を設計することが学校の役割だと思います。', 'room-evaluation-curriculum--community--non-cognitive-skills-t1'),
  ('room-evaluation-curriculum--community--non-cognitive-skills', '家庭のしつけと学校教育の境界が曖昧で、どこまで踏み込むか迷います。', 'room-evaluation-curriculum--community--non-cognitive-skills-t1'),
  ('room-children-rights-discipline--community--school-rules-guidance', '自分たちで決めたルールは守る意識も高まる。生徒会で議論する価値は大きいです。', 'room-children-rights-discipline--community--school-rules-guidance-t1'),
  ('room-children-rights-discipline--community--school-rules-guidance', '全部任せるのではなく、安全に関わる線は大人が守る。', 'room-children-rights-discipline--community--school-rules-guidance-t1'),
  ('room-children-rights-discipline--community--school-rules-guidance', '『なぜこの校則があるのか』を子どもと一緒に問い直すことそのものが、生きた主権者教育になる。守らせる対象ではなく考える教材として扱えば、理不尽な決まりも自然と整理されていくと思います。', 'room-children-rights-discipline--community--school-rules-guidance-t1'),
  ('room-children-rights-discipline--community--school-rules-guidance', '中学のとき、意味のない校則に疑問でした。', 'room-children-rights-discipline--community--school-rules-guidance-t1'),
  ('room-children-rights-discipline--community--bullying-prevention', '『重大かどうか』を後から判断していては手遅れになる。本人が苦痛を訴えた時点で初期対応に動くのが原則で、線引きの議論が初動を遅らせる口実になってはいけません。', 'room-children-rights-discipline--community--bullying-prevention-t1'),
  ('room-children-rights-discipline--community--bullying-prevention', '組織で抱え、担任一人に背負わせないことが第一。', 'room-children-rights-discipline--community--bullying-prevention-t1'),
  ('room-children-rights-discipline--community--bullying-prevention', '保護者としては、基準より『すぐ動いてくれるか』を一番見ています。', 'room-children-rights-discipline--community--bullying-prevention-t1'),
  ('room-children-rights-discipline--community--school-refusal-support', '学校がすべてではない、と私は経験から思います。', 'room-children-rights-discipline--community--school-refusal-support-t1'),
  ('room-children-rights-discipline--community--school-refusal-support', 'フリースクールやオンライン学習を出席として柔軟に認める動きは広がっている。大事なのは『どこで学ぶか』より『学び続けられるか』。本人が安心できる場を複数用意することが先だと思います。', 'room-children-rights-discipline--community--school-refusal-support-t1'),
  ('room-children-rights-discipline--community--school-refusal-support', '認める一方で、学びの機会が長期間失われないよう見守るバランスが難しいです。', 'room-children-rights-discipline--community--school-refusal-support-t1'),
  ('room-children-rights-discipline--community--school-refusal-support', '選択肢があるだけで親子の安心感が違います。', 'room-children-rights-discipline--community--school-refusal-support-t1'),
  ('room-children-rights-discipline--community--smartphone-sns', '災害時の連絡手段として、持ち込み自体は認めざるを得ない時代だと思います。', 'room-children-rights-discipline--community--smartphone-sns-t1'),
  ('room-children-rights-discipline--community--smartphone-sns', '授業中の扱いをどう管理するかが本丸です。', 'room-children-rights-discipline--community--smartphone-sns-t1'),
  ('room-children-rights-discipline--community--smartphone-sns', '全面禁止は隠れて使う子を増やすだけ。むしろ『どう付き合うか』を学ぶ教材として、ルールを子どもと一緒に作る方が教育的だと思います。取り上げて終わりにしないことが大事です。', 'room-children-rights-discipline--community--smartphone-sns-t1'),
  ('room-children-rights-discipline--community--smartphone-sns', '持たせる以上、家庭でのルール作りも要りますね。', 'room-children-rights-discipline--community--smartphone-sns-t1'),
  ('room-diversity-inclusion--community--inclusive-special-needs', '理念を支えるのは結局人員。介助員や支援員の配置を拡充しない限り、『配慮』が現場の負担増だけで終わってしまう。どこから予算を持ってくるかまで踏み込んで議論したいです。', 'room-diversity-inclusion--community--inclusive-special-needs-t1'),
  ('room-diversity-inclusion--community--inclusive-special-needs', '『特別扱い』ではなく当然の権利だと捉えたい。', 'room-diversity-inclusion--community--inclusive-special-needs-t1'),
  ('room-diversity-inclusion--community--inclusive-special-needs', '周りの子への説明や理解づくりもセットでないと、かえって本人が浮いてしまいます。', 'room-diversity-inclusion--community--inclusive-special-needs-t1'),
  ('room-diversity-inclusion--community--multicultural-foreign-roots', '翻訳AIや多言語教材で、少人数の言語にも現実的に対応できる時代になりました。', 'room-diversity-inclusion--community--multicultural-foreign-roots-t1'),
  ('room-diversity-inclusion--community--multicultural-foreign-roots', 'ツールで日常会話は回っても、教科の学習言語や進路の相談は別物。専門の加配教員を増やさないと、結局その子が進学でつまずく。日本語を身につける支援とセットで進めることが欠かせないと思います。', 'room-diversity-inclusion--community--multicultural-foreign-roots-t1'),
  ('room-teacher-school-system--community--teacher-work-style-reform', 'まず『前例だから』で続いている行事の見直しを。', 'room-teacher-school-system--community--teacher-work-style-reform-t1'),
  ('room-teacher-school-system--community--teacher-work-style-reform', '『子どものため』という言葉が、あらゆる業務を断れなくする魔法の言葉になっている。本当に必要かを問い直し、部活や事務作業は外部委託やデジタル化で減らす。教員が倒れては本末転倒だと思います。', 'room-teacher-school-system--community--teacher-work-style-reform-t1'),
  ('room-teacher-school-system--community--teacher-work-style-reform', '保護者対応や調査・報告の多さも相当な負担。ここを国レベルで減らしてほしいです。', 'room-teacher-school-system--community--teacher-work-style-reform-t1'),
  ('room-teacher-school-system--community--teacher-work-style-reform', '先生が疲れていると子どもにしわ寄せがきます。', 'room-teacher-school-system--community--teacher-work-style-reform-t1'),
  ('room-teacher-school-system--community--school-consolidation', '数の論理だけで決めると、地域から学校という核が消えてしまいます。', 'room-teacher-school-system--community--school-consolidation-t1'),
  ('room-teacher-school-system--community--school-consolidation', '小規模校は一人ひとりに目が届く良さがある一方、同年代の集団で学ぶ経験や多様な意見に触れる機会は得にくい。通学負担とのトレードオフを、子どもの利益を軸に丁寧に話し合うべきだと思います。', 'room-teacher-school-system--community--school-consolidation-t1'),
  ('room-teacher-school-system--community--school-consolidation', '統廃合で送迎や見守りの負担が親に増えます。', 'room-teacher-school-system--community--school-consolidation-t1'),
  ('room-subject-teaching--community--japanese-language', '作文の下書きにAIを使い、推敲の視点を学ぶ使い方は有効だと感じます。', 'room-subject-teaching--community--japanese-language-t1'),
  ('room-subject-teaching--community--japanese-language', 'AIに要約や添削をさせると、子どもが自分で読む・書く機会を奴いかねない。便利だからこそ、まず自分の言葉で書いてからAIと照らす順序を崩さないこと。読書の量そのものも減らさないでほしいです。', 'room-subject-teaching--community--japanese-language-t1'),
  ('room-subject-teaching--community--mathematics', '計算ドリルの個別最適化は、AIの得意分野です。', 'room-subject-teaching--community--mathematics-t1'),
  ('room-subject-teaching--community--mathematics', '答えだけでなく『なぜその解き方か』を説明させると思考が深まる。逆に途中式をAIに丸投げすると、つまずきが見えなくなる。教員が学習の跡を確認できる使い方を設計したいです。', 'room-subject-teaching--community--mathematics-t1'),
  ('room-subject-teaching--community--science', '危険な実験のシミュレーションなど、AIで安全に試せる場面は多いです。', 'room-subject-teaching--community--science-t1'),
  ('room-subject-teaching--community--social-studies', '統計データの読み解きや歴史資料の比較に、AIは強力な道具になる。ただ『AIが言ったから正しい』では本末転倒で、出典を確かめ複数の見方を突き合わせる力をセットで育てるのが社会科の役目だと思います。', 'room-subject-teaching--community--social-studies-t1'),
  ('room-subject-teaching--community--english-foreign-language', '発音やスピーキングの練習相手として、AIは恥ずかしがらずに使えるのが利点。', 'room-subject-teaching--community--english-foreign-language-t1'),
  ('room-subject-teaching--community--english-foreign-language', '翻訳AIの精度が上がった今、英語学習の意味づけが問われる。AIは練習の補助に使いつつ、その場で人と心を通わせる体験の価値を伝えたい。道具に頼り切らない設計が大事だと思います。', 'room-subject-teaching--community--english-foreign-language-t1'),
  ('room-subject-teaching--community--english-foreign-language', '間違いを気にせず話せる相手ができるのは大きいです。', 'room-subject-teaching--community--english-foreign-language-t1'),
  ('room-subject-teaching--community--moral-education', '多様な立場の意見をAIに出させ、議論の材料にするのは面白い試みです。', 'room-subject-teaching--community--moral-education-t1'),
  ('room-subject-teaching--community--pe-health', '動作をAIで撮って分析すると、苦手な子も上達を実感できます。', 'room-subject-teaching--community--pe-health-t1'),
  ('room-subject-teaching--community--music-art', 'AIで作曲や画像生成を体験させると、表現の入り口が広がります。', 'room-subject-teaching--community--music-art-t1'),
  ('room-subject-teaching--community--home-economics-technology', '献立の栄養計算や被服の型紙づくりなど、AIで効率化できる作業は多いです。', 'room-subject-teaching--community--home-economics-technology-t1'),
  ('room-subject-teaching--community--integrated-inquiry-time', '調べてまとめるだけならAIが代行できる時代。だからこそ総合では『どんな問いを立てるか』『得た答えをどう吟味するか』に重心を移し、AIは情報収集の相棒として位置づけたいです。', 'room-subject-teaching--community--integrated-inquiry-time-t1'),
  ('room-subject-teaching--community--integrated-inquiry-time', '教科横断のテーマ設定にAIの助けは大きい。', 'room-subject-teaching--community--integrated-inquiry-time-t1'),
  ('room-subject-teaching--community--information-subject', 'プログラミングの初学者がAIに質問しながら学べるのは大きな利点です。', 'room-subject-teaching--community--information-subject-t1'),
  ('room-subject-teaching--community--information-subject', 'ただAIにコードを丸ごと書かせると、なぜ動くかを理解しないまま進んでしまう。生成物を読み解き、直し、説明できる力をセットで育てないと『使えるが分からない』状態に陥ると思います。', 'room-subject-teaching--community--information-subject-t1'),
  ('room-subject-teaching--community--information-subject', '情報モラルも実例で学べる教材になります。', 'room-subject-teaching--community--information-subject-t1'),
  ('room-subject-teaching--community--career-guidance', '適性や選択肢をAIで可視化するのは有効だが、最後に『どう生きたいか』を考えるのは本人。データが示す『向いている』に流されず、本人の主体性を育てる支援とセットで使いたいです。', 'room-subject-teaching--community--career-guidance-t1'),
  ('room-subject-teaching--community--career-guidance', '偏差値だけでない進路の見せ方ができそうです。', 'room-subject-teaching--community--career-guidance-t1'),
  ('room-ai-technology--community--digital-textbook', '長文をじっくり読む力は、紙のほうが育ちやすいと感じます。', 'room-ai-technology--community--digital-textbook-t2'),
  ('room-ai-technology--community--digital-textbook', 'スクロールで流し読みになりやすく、深い読解には不利という指摘がある一方、辞書連携や音声読み上げで読みを支えられる面もある。デジタルか紙かではなく、読む目的に応じて使い分ける設計が要ると思います。', 'room-ai-technology--community--digital-textbook-t2'),
  ('room-ai-technology--community--digital-textbook', '目への負担や姿勢の問題も、読解以前に気になるところです。', 'room-ai-technology--community--digital-textbook-t2'),
  ('room-ai-technology--community--edtech-adoption', 'もはや民間サービスなしに学校は回らない。問題は依存の『質』だと思います。', 'room-ai-technology--community--edtech-adoption-t2'),
  ('room-ai-technology--community--edtech-adoption', '特定の企業に深く依存すると、値上げやサービス終了のたびに現場が振り回される。データの持ち出しやすさ、乗り換えのしやすさを契約時に確認しておくことが、長期的なリスク管理になると思います。', 'room-ai-technology--community--edtech-adoption-t2'),
  ('room-ai-technology--community--ai-literacy-moral', '『一次情報にあたる』習慣を低学年から。', 'room-ai-technology--community--ai-literacy-moral-t2'),
  ('room-ai-technology--community--ai-literacy-moral', '誤情報や生成AIによる偽画像が湢れる今、見抜く力は必須スキル。ただ『疑え』と教えるだけでは萎縮する。複数の情報源を照らし合わせ、確からしさを自分で確かめる手順を、具体例で繰り返し練習させたいです。', 'room-ai-technology--community--ai-literacy-moral-t2'),
  ('room-ai-technology--community--ai-literacy-moral', '家庭でもSNSの情報を鵜呑みにしがち。学校で学んだことを家でも話せるといいです。', 'room-ai-technology--community--ai-literacy-moral-t2'),
  ('room-ai-technology--community--ai-literacy-moral', '『無料』の裏側を考える教材にもなります。', 'room-ai-technology--community--ai-literacy-moral-t2'),
  ('room-ai-technology--community--personalized-learning', '基礎の反復はアダプティブ教材に任せ、浮いた時間を話し合いに回すのが現実的です。', 'room-ai-technology--community--personalized-learning-t2'),
  ('room-ai-technology--community--personalized-learning', '個別最適と一斉授業は対立しない。一人で進める時間と、みんなで考えを交わす時間を意図的に組み合わせることで、効率と深まりの両方が得られる。教員の授業デザイン力が問われるところだと思います。', 'room-ai-technology--community--personalized-learning-t2'),
  ('room-evaluation-curriculum--community--inquiry-pbl', '成果物の完成度で測ると、見栄えのよい発表が評価されがち。本当に見たいのは『調べる途中で考えが変わった瞬間』を語れるか。思考の跡を評価する視点への転換が必要だと思います。', 'room-evaluation-curriculum--community--inquiry-pbl-t2'),
  ('room-evaluation-curriculum--community--inquiry-pbl', 'ルーブリックを生徒と共有すると公正になります。', 'room-evaluation-curriculum--community--inquiry-pbl-t2'),
  ('room-evaluation-curriculum--community--homework', '丸つけは自動採点に任せ、教員は見取りに集中したい。', 'room-evaluation-curriculum--community--homework-t2'),
  ('room-evaluation-curriculum--community--homework', '提出状況の管理や丸つけに時間を取られ、肝心の『つまずきの分析』まで手が回らないのが現場の悩み。AIや相互採点を取り入れ、教員は一人ひとりの理解度を見る時間に振り向けるべきだと思います。', 'room-evaluation-curriculum--community--homework-t2'),
  ('room-evaluation-curriculum--community--homework', '宿題の提出状況から家庭の状況が見える面もあり、悩ましいところです。', 'room-evaluation-curriculum--community--homework-t2'),
  ('room-evaluation-curriculum--community--course-of-study-revision', '二項対立で語るより、何を核として残すかを先に決めるべきだと思います。', 'room-evaluation-curriculum--community--course-of-study-revision-t2'),
  ('room-evaluation-curriculum--community--course-of-study-revision', '『詰め込み』批判でゆとりに振れ、学力低下批判でまた詰め込みに戻る——この振り子を繰り返してきた。大事なのは量の調整ではなく、深く学ぶ時間をどう確保するか。現場の声を入れた議論が要ります。', 'room-evaluation-curriculum--community--course-of-study-revision-t2'),
  ('room-evaluation-curriculum--community--course-of-study-revision', '範囲が広がり続けて、子の負担が心配です。', 'room-evaluation-curriculum--community--course-of-study-revision-t2'),
  ('room-evaluation-curriculum--community--non-cognitive-skills', '数値で測ろうとした瞬間、本来の良さが歪む危うさがあります。', 'room-evaluation-curriculum--community--non-cognitive-skills-t2'),
  ('room-evaluation-curriculum--community--non-cognitive-skills', '粘り強さや協働性は、テストのように点数化しにくい。だからといって評価しないと指導の手がかりも失う。観察記録やポートフォリオで『変化の過程』を見取る、緩やかな評価が現実解だと思います。', 'room-evaluation-curriculum--community--non-cognitive-skills-t2'),
  ('room-children-rights-discipline--community--school-rules-guidance', '『なぜこのルール？』と問い直すことから。', 'room-children-rights-discipline--community--school-rules-guidance-t2'),
  ('room-children-rights-discipline--community--school-rules-guidance', '下着の色指定や地毛証明など、合理的な説明ができない決まりは見直すべき。ただ現場には『ルールが多いほうが指導は楽』という本音もある。だからこそ目的を定期的に問い直す仕組みが要ると思います。', 'room-children-rights-discipline--community--school-rules-guidance-t2'),
  ('room-children-rights-discipline--community--school-rules-guidance', '安全や他者への配慮に関わる線は残し、それ以外は子どもと一緒に。', 'room-children-rights-discipline--community--school-rules-guidance-t2'),
  ('room-children-rights-discipline--community--school-rules-guidance', '中学のとき、意味不明な校則が多かった。', 'room-children-rights-discipline--community--school-rules-guidance-t2'),
  ('room-children-rights-discipline--community--bullying-prevention', '加害児童の背景には、本人の困りごとが隠れていることが多い。罰するだけでは繰り返す。ただし被害児童の安全確保が最優先で、両者を切り離したうえで加害側にも丁寧に関わる二段構えが要ると思います。', 'room-children-rights-discipline--community--bullying-prevention-t2'),
  ('room-children-rights-discipline--community--bullying-prevention', 'まず被害児童が安心できる環境を。', 'room-children-rights-discipline--community--bullying-prevention-t2'),
  ('room-children-rights-discipline--community--bullying-prevention', '担任一人で抱えず、組織と外部機関で対応する体制が不可欠です。', 'room-children-rights-discipline--community--bullying-prevention-t2'),
  ('room-children-rights-discipline--community--school-refusal-support', '『復帰』をゴールにすると本人を追い詰めます。', 'room-children-rights-discipline--community--school-refusal-support-t2'),
  ('room-children-rights-discipline--community--school-refusal-support', '目標は学校に戻ることではなく、社会的に自立すること。学校以外の学びの場で力をつける道もある。ただ見守るだけで機会が失われないよう、本人のペースに合わせた選択肢を複数示すことが大事だと思います。', 'room-children-rights-discipline--community--school-refusal-support-t2'),
  ('room-children-rights-discipline--community--school-refusal-support', '親としては『戻ってほしい』と『無理させたくない』で揺れます。', 'room-children-rights-discipline--community--school-refusal-support-t2'),
  ('room-children-rights-discipline--community--smartphone-sns', '放課後・校外のトラブルでも、学校に持ち込まれれば対応せざるを得ません。', 'room-children-rights-discipline--community--smartphone-sns-t2'),
  ('room-children-rights-discipline--community--smartphone-sns', '『学校外のことだから』と線を引きたくても、子どもの人間関係はつながっている。介入しすぎれば家庭の領分を侵し、放置すれば被害が広がる。家庭や専門機関と連携する前提で関わるしかないと思います。', 'room-children-rights-discipline--community--smartphone-sns-t2'),
  ('room-children-rights-discipline--community--smartphone-sns', '保護者としては学校だけに頼れません。', 'room-children-rights-discipline--community--smartphone-sns-t2'),
  ('room-children-rights-discipline--community--smartphone-sns', '匿名で相談できる窓口があると助かります。', 'room-children-rights-discipline--community--smartphone-sns-t2'),
  ('room-diversity-inclusion--community--inclusive-special-needs', '分けるか混ぜるかの二択ではなく、その子にとって何が学びやすいかが基準。交流の機会を保ちつつ必要な支援は手厚くする柔軟な運用が理想だが、それを支える人員が足りないのが最大の壁です。', 'room-diversity-inclusion--community--inclusive-special-needs-t2'),
  ('room-diversity-inclusion--community--inclusive-special-needs', '本人と保護者の希望を一番に。', 'room-diversity-inclusion--community--inclusive-special-needs-t2'),
  ('room-diversity-inclusion--community--inclusive-special-needs', '周りの子にとっても、多様な仲間と過ごす経験は財産になります。', 'room-diversity-inclusion--community--inclusive-special-needs-t2'),
  ('room-diversity-inclusion--community--multicultural-foreign-roots', '母語の力は、実は日本語の習得を支える土台にもなります。', 'room-diversity-inclusion--community--multicultural-foreign-roots-t2'),
  ('room-diversity-inclusion--community--multicultural-foreign-roots', '日本語指導を優先するあまり母語を切り捨てると、家族との会話やアイデンティティが揺らぐ。母語・母文化を保てる場を地域や保護者と協力して用意することが、結果的にその子の学びと安定につながると思います。', 'room-diversity-inclusion--community--multicultural-foreign-roots-t2'),
  ('room-teacher-school-system--community--teacher-work-style-reform', '上限を図っても、持ち帰り仕事に変わるだけでは意味がありません。', 'room-teacher-school-system--community--teacher-work-style-reform-t2'),
  ('room-teacher-school-system--community--teacher-work-style-reform', '規制に実効性を持たせるには、業務そのものを減らすしかない。勤務時間の記録を厳格にし、削った業務を管理職が明示する。『時間内に終わらない量』を放置したまま上限だけ設けても、現場は苦しくなるだけです。', 'room-teacher-school-system--community--teacher-work-style-reform-t2'),
  ('room-teacher-school-system--community--teacher-work-style-reform', '部活の地域移行も鍵になります。', 'room-teacher-school-system--community--teacher-work-style-reform-t2'),
  ('room-teacher-school-system--community--school-consolidation', '学校は選挙の投票所、防災拠点、見守りの場として地域を支えてきた。統廃合で消えると、その機能ごと失われる。教育の効率だけでなく、地域インフラとしての役割も含めて判断すべきだと思います。', 'room-teacher-school-system--community--school-consolidation-t2'),
  ('room-teacher-school-system--community--school-consolidation', '残すなら維持コストの議論も避けられません。', 'room-teacher-school-system--community--school-consolidation-t2'),
  ('room-subject-teaching--community--japanese-language', '読めれば十分、書きは最小限でいいのでは。', 'room-subject-teaching--community--japanese-language-t2'),
  ('room-subject-teaching--community--japanese-language', '手で書く過程で字の構造を覚え、読みの力にもつながるという面がある。一方で社会では入力が主流。すべてを手書きで反復させるより、要点を絞って、デジタル入力の指導とバランスを取るのが現実的だと思います。', 'room-subject-teaching--community--japanese-language-t2'),
  ('room-subject-teaching--community--japanese-language', '手書きには集中力や丁寧さを育てる側面もあると感じます。', 'room-subject-teaching--community--japanese-language-t2'),
  ('room-subject-teaching--community--mathematics', '計算手順の理解が先。そのうえで電卓を使うなら有効だと思います。', 'room-subject-teaching--community--mathematics-t2'),
  ('room-subject-teaching--community--mathematics', '電卓やアプリに頼ると計算力が落ちる、という懸念は根強い。でも社会では当たり前に使う道具。基礎の習得段階と、データ処理や応用の段階で、使わせ方を切り替える設計が要ると思います。', 'room-subject-teaching--community--mathematics-t2'),
  ('room-subject-teaching--community--science', '知識の土台がなければ、探究は浅い調べ学習で終わる。逆に暗記だけでは使えない。基礎を効率よく固め、その知識を探究で活かす循環を作るのが、限られた時数の中での現実解だと思います。', 'room-subject-teaching--community--science-t2'),
  ('room-subject-teaching--community--science', '両方が要る、というのが現場の実感です。', 'room-subject-teaching--community--science-t2'),
  ('room-subject-teaching--community--social-studies', '現代の論争的テーマを避けると、社会から切り離された学びになる。ただ扱う以上、教員の政治的中立性をどう保つかが要。結論を出すのではなく、複数の見方を提示し考えさせる訓練が教員側にも必要です。', 'room-subject-teaching--community--social-studies-t2'),
  ('room-subject-teaching--community--social-studies', '家庭の価値観との摩擦も生じやすい。', 'room-subject-teaching--community--social-studies-t2'),
  ('room-subject-teaching--community--social-studies', '答えのない問いを話し合う経験こそ、これからの社会で要る力です。', 'room-subject-teaching--community--social-studies-t2'),
  ('room-subject-teaching--community--english-foreign-language', '文法・読解の土台がないと、会話も深まらないのが実感です。', 'room-subject-teaching--community--english-foreign-language-t2'),
  ('room-subject-teaching--community--english-foreign-language', '会話偏重で文法を軽視すると、込み入った内容を正確に伝えられなくなる。逆に文法ばかりでは話せない。翻訳AIがある今だからこそ、自分の言葉で伝える楽しさを軸に、両方をつなぐ設計が要ると思います。', 'room-subject-teaching--community--english-foreign-language-t2'),
  ('room-subject-teaching--community--moral-education', '『正解』を当てにいく道徳では意味がないと思います。', 'room-subject-teaching--community--moral-education-t2'),
  ('room-subject-teaching--community--moral-education', '評価が入ったことで、子どもが教員の望む答えを書く傾向が強まった。本来は答えのない問いに向き合い、揺れながら考える時間のはず。点数化しにくくても、考えるプロセスそのものを大事にする設計に戻したいです。', 'room-subject-teaching--community--moral-education-t2'),
  ('room-subject-teaching--community--pe-health', '順位だけ強調すると、運動嫩いを生むだけになりがちです。', 'room-subject-teaching--community--pe-health-t2'),
  ('room-subject-teaching--community--pe-health', '競争は意欲を引き出す面もあるが、勝ち負けが固定化すると苦手な子は早々に諸める。順位より『自分の記録がどう伸びたか』を見える化するなど、一人ひとりの達成を軸にする工夫が要ると思います。', 'room-subject-teaching--community--pe-health-t2'),
  ('room-subject-teaching--community--pe-health', '『できた』体験のほうが長く残ります。', 'room-subject-teaching--community--pe-health-t2'),
  ('room-subject-teaching--community--music-art', '基礎技能がないと自由な表現も広がらない一方、技術練習ばかりでは『やらされ』になり、表現する喜びが薄れる。まず楽しいと感じる入り口を作り、必要な技能はその中で身につける順序が大事だと思います。', 'room-subject-teaching--community--music-art-t2'),
  ('room-subject-teaching--community--home-economics-technology', '調理や金銭管理など、生きる力は学校でも扱う価値があります。', 'room-subject-teaching--community--home-economics-technology-t2'),
  ('room-subject-teaching--community--home-economics-technology', '本来は家庭で身につくはずのことが学校に求められる背景には、家庭の余裕のなさがある。学校が全部抱えるのは無理だが、最低限の生活スキルを学ぶ場を保障することは、格差を埋める意味で意義があると思います。', 'room-subject-teaching--community--home-economics-technology-t2'),
  ('room-subject-teaching--community--integrated-inquiry-time', '教科の壁を越えた学びは理想だが、時間割や教員配置の制約で『やりにくい』のが現実。総合の時間を軸に、各教科の知識を持ち寄るテーマを設定すると、現場でも回せる横断設計になると思います。', 'room-subject-teaching--community--integrated-inquiry-time-t2'),
  ('room-subject-teaching--community--information-subject', '技術だけ教えても、使い方の倫理が伴わなければ危うい。両輪です。', 'room-subject-teaching--community--information-subject-t2'),
  ('room-subject-teaching--community--information-subject', 'プログラミングなどの技術力は将来の選択肢を広げるが、個人情報や著作権、誹謗中傷への意識が抜けると、技術が凶器になりかねない。モラルと技術は切り離さず、実例を通して同時に学ばせたいです。', 'room-subject-teaching--community--information-subject-t2'),
  ('room-subject-teaching--community--career-guidance', '偏差値は分かりやすい指標だが、それだけで進路を決めると『入れる学校』に流される。本人が何に夢中になれるかを軸に、多様な進路情報を示すことが、変化の時代の進路指導だと思います。', 'room-subject-teaching--community--career-guidance-t2'),
  ('room-subject-teaching--community--career-guidance', '数値以外の物差しを親子で持ちたい。', 'room-subject-teaching--community--career-guidance-t2'),
  ('room-subject-teaching--community--career-guidance', '脱却したくても、入試制度が偏差値前提だと現場も動きにくい。', 'room-subject-teaching--community--career-guidance-t2'),
  ('room-subject-teaching--community--career-guidance', '本人の『好き』を一番に考えたい。', 'room-subject-teaching--community--career-guidance-t2'),
  ('room-ai-technology--community--digital-textbook', '二者択一でなく、目的で使い分けるのが現実的です。', 'room-ai-technology--community--digital-textbook-t3'),
  ('room-ai-technology--community--digital-textbook', '集中して読む場面は紙、検索や動画連動・共同編集はデジタル、と場面で選ぶのが自然。ただ使い分けの基準を現場の裁量に丸投げすると中途半端になりがちなので、学校として一定の方針を示してほしいです。', 'room-ai-technology--community--digital-textbook-t3'),
  ('room-ai-technology--community--digital-textbook', '家でも学校でもデジタルだと、紙の本をめくる経験そのものが減ります。', 'room-ai-technology--community--digital-textbook-t3'),
  ('room-ai-technology--community--edtech-adoption', '無料サービスは『データが商品』のことが多い。何と引き換えかを見て使いたい。', 'room-ai-technology--community--edtech-adoption-t3'),
  ('room-ai-technology--community--edtech-adoption', '現場が無料だからと個別に導入すると、学校全体でデータ管理がバラバラになる。利用規約のチェック体制を整え、どのサービスを使うか組織で判断する仕組みが要る。安さの裏のリスクを見ぬく目が大事です。', 'room-ai-technology--community--edtech-adoption-t3'),
  ('room-ai-technology--community--ai-literacy-moral', '情報モラルは学校か家庭かではなく、両者が同じ言葉で語ることが大事。学校が見取り図を示し、家庭が日常で実践する分担が現実的。トラブルは家庭で起きて学校に持ち込まれることが多く、連携しないと実効性がありません。', 'room-ai-technology--community--ai-literacy-moral-t3'),
  ('room-ai-technology--community--ai-literacy-moral', '家庭に丸投げしても、詳しくない保護者は多い。', 'room-ai-technology--community--ai-literacy-moral-t3'),
  ('room-ai-technology--community--ai-literacy-moral', '子どものほうが親よりデバイスに詳しい現状では、学校の専門的な支援が要ります。', 'room-ai-technology--community--ai-literacy-moral-t3'),
  ('room-ai-technology--community--personalized-learning', '『点数が上がる』だけの最適化に陥らないか。誰のための最適化かが問われます。', 'room-ai-technology--community--personalized-learning-t3'),
  ('room-ai-technology--community--personalized-learning', '最適化のアルゴリズムがブラックボックスのままだと、なぜその問題が出たのか説明できない。透明性の確保が必須で、何より子ども本人が『どう学びたいか』を言える状態でないと、誰かの都合の最適化になってしまいます。', 'room-ai-technology--community--personalized-learning-t3'),
  ('room-evaluation-curriculum--community--inquiry-pbl', '両者は対立しません。むしろ補い合う関係です。', 'room-evaluation-curriculum--community--inquiry-pbl-t3'),
  ('room-evaluation-curriculum--community--inquiry-pbl', '教科で身につけた知識を探究で使い、探究で生まれた問いを教科で深める循環が理想。ただ限られた授業時数で両方を成立させるのは至難で、基礎をデジタルで効率化し、浮いた時間を探究に回す工夫が要ります。', 'room-evaluation-curriculum--community--inquiry-pbl-t3'),
  ('room-evaluation-curriculum--community--inquiry-pbl', '受験を控えると、探究に時間を割いて大丈夫か不安になります。', 'room-evaluation-curriculum--community--inquiry-pbl-t3'),
  ('room-evaluation-curriculum--community--homework', '宿題が家庭のサポート力を前提にした瞬間、格差を広げる。共働きやひとり親では見てあげる余裕がないのが現実で、『家でやる前提』の設計を見直し、学校や地域でやれる場を充実させるべきだと思います。', 'room-evaluation-curriculum--community--homework-t3'),
  ('room-evaluation-curriculum--community--homework', '学校内で完結する学習時間を確保したい。', 'room-evaluation-curriculum--community--homework-t3'),
  ('room-evaluation-curriculum--community--homework', '放課後の学習支援を充実させれば、格差はかなり緩和できます。', 'room-evaluation-curriculum--community--homework-t3'),
  ('room-evaluation-curriculum--community--homework', '共働きだと見る時間がないのが現実です。', 'room-evaluation-curriculum--community--homework-t3'),
  ('room-evaluation-curriculum--community--course-of-study-revision', '『増やす』議論より『何を処理できるか』を先に決めるべきです。', 'room-evaluation-curriculum--community--course-of-study-revision-t3'),
  ('room-evaluation-curriculum--community--course-of-study-revision', '情報・防災・金融・言語と必要なものは増える一方。だが現場のキャパシティを超えた詰め込みはもう限界で、増やすなら授業時数か教員数も同時に議論しないと、しわ寄せが現場に来るだけです。', 'room-evaluation-curriculum--community--course-of-study-revision-t3'),
  ('room-evaluation-curriculum--community--non-cognitive-skills', '優劣ではなく車の両輪。優先順位の発想自体が学びを狭めます。', 'room-evaluation-curriculum--community--non-cognitive-skills-t3'),
  ('room-evaluation-curriculum--community--non-cognitive-skills', '現場で限られた時間を配分する以上、どちらに重きを置くかの選択は避けられない。結局テストで測れる認知が優先されがちだが、社会に出てから効いてくるのは非認知の力。長い目で見る視点を忘れたくないです。', 'room-evaluation-curriculum--community--non-cognitive-skills-t3'),
  ('room-children-rights-discipline--community--school-rules-guidance', '『安全と学習環境を守るため』にあるはず。昔からあるだけの決まりは外していい。', 'room-children-rights-discipline--community--school-rules-guidance-t3'),
  ('room-children-rights-discipline--community--school-rules-guidance', '『何のために』を生徒と一緒に考えることそのものが、生きた主権者教育になる。守らせる対象ではなく考える教材として扱えば、理不尽な校則は自然と整理される。理由を説明できるかを基準にすればいいと思います。', 'room-children-rights-discipline--community--school-rules-guidance-t3'),
  ('room-children-rights-discipline--community--school-rules-guidance', 'ルールが多いほうが指導は楽、という本音もあります。', 'room-children-rights-discipline--community--school-rules-guidance-t3'),
  ('room-children-rights-discipline--community--school-rules-guidance', '理由を説明できる校則なら納得できます。', 'room-children-rights-discipline--community--school-rules-guidance-t3'),
  ('room-children-rights-discipline--community--bullying-prevention', '『言い出せない子』の声を拾う点で有効。匿名で通報できると、告げ口と思われるのを恐れる子の助けになる。ただ『アプリさえ入れれば安心』にならないよう、受け皿となる人の体制が伴うことが前提だと思います。', 'room-children-rights-discipline--community--bullying-prevention-t3'),
  ('room-children-rights-discipline--community--bullying-prevention', '誤検知や、監視と保護の境界が難しい。', 'room-children-rights-discipline--community--bullying-prevention-t3'),
  ('room-children-rights-discipline--community--bullying-prevention', '早期発見は安心だが、人のフォローがないと意味がありません。', 'room-children-rights-discipline--community--bullying-prevention-t3'),
  ('room-children-rights-discipline--community--school-refusal-support', '『問題」と見る視線そのものが子を追い詰めます。', 'room-children-rights-discipline--community--school-refusal-support-t3'),
  ('room-children-rights-discipline--community--school-refusal-support', '『学校が合わなかった』という中立的な見方も必要。一方で学びの機会が長期間失われるのを問題ないと言い切るのも危うい。問題視しないことと放置しないことは両立するので、安心できる場を複数用意して学びを繋ぎたいです。', 'room-children-rights-discipline--community--school-refusal-support-t3'),
  ('room-children-rights-discipline--community--school-refusal-support', '見守りつつ学びを保障するバランスが難しいところです。', 'room-children-rights-discipline--community--school-refusal-support-t3'),
  ('room-children-rights-discipline--community--school-refusal-support', '見方を変えるだけで親子の心が軽くなります。', 'room-children-rights-discipline--community--school-refusal-support-t3'),
  ('room-children-rights-discipline--community--smartphone-sns', '学校・家庭・本人の三者が協力するしかないテーマだと思います。', 'room-children-rights-discipline--community--smartphone-sns-t3'),
  ('room-children-rights-discipline--community--smartphone-sns', '本人が『自分でコントロールする力』を身につけるのがゴール。ただ依存性の高い設計のSNSやゲームに子ども一人で抵抗するのは酷で、大人と仕組みのサポートが要る。誰かに丸投げした瞬間にうまくいかなくなります。', 'room-children-rights-discipline--community--smartphone-sns-t3'),
  ('room-children-rights-discipline--community--smartphone-sns', '親世代はスマホがなく、教え方が分からないです。', 'room-children-rights-discipline--community--smartphone-sns-t3'),
  ('room-diversity-inclusion--community--inclusive-special-needs', '理念を支えるのは人員。介助員や支援員の配置を拡充しない限り、現場の負担だけが増す。人員確保には財源が要るので、どこから予算を持ってくるかまで踏み込まないと、理念を語るだけで現場が疲弊します。', 'room-diversity-inclusion--community--inclusive-special-needs-t3'),
  ('room-diversity-inclusion--community--inclusive-special-needs', '地域のボランティアや学生サポーターの活用も。', 'room-diversity-inclusion--community--inclusive-special-needs-t3'),
  ('room-diversity-inclusion--community--inclusive-special-needs', '人手不足で『インクルーシブ』が名ばかりになっている例も見てきました。', 'room-diversity-inclusion--community--inclusive-special-needs-t3'),
  ('room-diversity-inclusion--community--multicultural-foreign-roots', '翻訳AIや多言語教材で、少人数の言語にも現実的に対応できる時代です。', 'room-diversity-inclusion--community--multicultural-foreign-roots-t3'),
  ('room-diversity-inclusion--community--multicultural-foreign-roots', 'ツールで日常会話は回っても、心のケアや進路相談など微妙なニュアンスは人間が必要。どこまでをAIに任せるかは地域により、集住地域は人の配置、点在地域はAIを、とリソースに応じて柔軟に考えるのが現実的だと思います。', 'room-diversity-inclusion--community--multicultural-foreign-roots-t3'),
  ('room-teacher-school-system--community--teacher-work-style-reform', '『子どものため』が、業務を断れなくする魔法の言葉に。', 'room-teacher-school-system--community--teacher-work-style-reform-t3'),
  ('room-teacher-school-system--community--teacher-work-style-reform', '動機が善意なだけに断りにくいが、教員が倒れては本末転倒。『これは本当に子どものためか、教員の自己満足か』を問う仕組みが要る。前例があるから、保護者が言うかも、で業務が増える構造を管理職が断ち切るべきです。', 'room-teacher-school-system--community--teacher-work-style-reform-t3'),
  ('room-teacher-school-system--community--teacher-work-style-reform', '先生が疲弊していると、結局子どもにしわ寄せがくると感じます。', 'room-teacher-school-system--community--teacher-work-style-reform-t3'),
  ('room-teacher-school-system--community--teacher-work-style-reform', '『やめる』判断こそ評価したい。', 'room-teacher-school-system--community--teacher-work-style-reform-t3'),
  ('room-teacher-school-system--community--school-consolidation', '通学負担の増加は、特に低学年や体力のない子に深刻。スクールバスの運行コストも含めて長期的な負担を試算すべき。送迎や見守り当番など保護者の負担も増えるので、家庭への影響も見てほしいです。', 'room-teacher-school-system--community--school-consolidation-t3'),
  ('room-teacher-school-system--community--school-consolidation', '移動時間をオンライン朝学に活かす例も。', 'room-teacher-school-system--community--school-consolidation-t3'),
  ('room-subject-teaching--community--japanese-language', 'パフォーマンス評価は不可欠だが、教員の負担が大きいのが課題です。', 'room-subject-teaching--community--japanese-language-t3'),
  ('room-subject-teaching--community--japanese-language', 'ペーパーテストで測れない力だからこそ、プレゼンや討論の機会を日常的に作るべき。評価の主観性はルーブリックの整備や複数の教員で見る仕組みで担保し、AIによる下書き評価の補助も現実解になります。', 'room-subject-teaching--community--japanese-language-t3'),
  ('room-subject-teaching--community--mathematics', '『なぜ数学を』には、論理的に考える力や物事を抽象化する力を養うため、と答えています。計算そのものは手段にすぎない。ただ学んでいる最中の生徒には届きにくいので、実生活や他教科とのつながりを見せると納得してくれます。', 'room-subject-teaching--community--mathematics-t3'),
  ('room-subject-teaching--community--mathematics', '統計やデータ分析など、使われる場面を見せたい。', 'room-subject-teaching--community--mathematics-t3'),
  ('room-subject-teaching--community--mathematics', '親も『なんで勉強するの』と聞かれて答えに詰まります。', 'room-subject-teaching--community--mathematics-t3'),
  ('room-subject-teaching--community--mathematics', '抽象論だけでは生徒は動きません。', 'room-subject-teaching--community--mathematics-t3'),
  ('room-subject-teaching--community--science', '『不思議』を体験する前に試験勉強になってしまうのが背景にあります。', 'room-subject-teaching--community--science-t3'),
  ('room-subject-teaching--community--science', '実験の準備・片付けに追われ、本来の『なぜ？』を考える時間が取れないのが現場の悩み。身近な現象や最新の科学トピックと結びつけると生徒の目の輝きが変わるので、教科書の順番だけでなく『今」と繋げる工夫が鍵です。', 'room-subject-teaching--community--science-t3'),
  ('room-subject-teaching--community--social-studies', '『投票の仕方』だけでなく、身近な課題を自分事として考え、合意形成する経験が本質。校則見直しなど身近な題材が最適で、結論を出すより複数の見方を扱う訓練が、教員側にも生徒側にも要ると思います。', 'room-subject-teaching--community--social-studies-t3'),
  ('room-subject-teaching--community--social-studies', '小中から『自分たちで決める』経験を。', 'room-subject-teaching--community--social-studies-t3'),
  ('room-subject-teaching--community--english-foreign-language', '翻訳AIがある今、英語を学ぶ意味は『その場で人と心を通わせる体験』にあります。', 'room-subject-teaching--community--english-foreign-language-t3'),
  ('room-subject-teaching--community--english-foreign-language', '翻訳AIの精度が上がり、『実用』だけを理由にしにくくなった。だが翻訳に頼ると微妙なニュアンスやその場のユーモアが伝わらない。言語を通した異文化理解など、新しい動機づけと、自分の言葉で話せる豊かさを伝えたいです。', 'room-subject-teaching--community--english-foreign-language-t3'),
  ('room-subject-teaching--community--english-foreign-language', '将来海外で働く可能性も考えたいです。', 'room-subject-teaching--community--english-foreign-language-t3'),
  ('room-subject-teaching--community--moral-education', '『どの価値が正しいか』ではなく『違う価値観の人とどう協力するか』を扱うべき。結論を出さない議論の価値を伝えたい。多様性を講じるなら、教員自身の価値観を押し付けない姿勢が不可欠だと思います。', 'room-subject-teaching--community--moral-education-t3'),
  ('room-subject-teaching--community--moral-education', '『普通』を前提にした道徳は誰かを傷つけます。', 'room-subject-teaching--community--moral-education-t3'),
  ('room-subject-teaching--community--pe-health', '『踏み込まない』ことでリスクが高まる領域。正確な知識を発達段階に応じて届けることが、結局は子どもを守る。ネットに誤った・過激な情報が溢れる今だからこそ、学校が安心できる情報源になってほしいです。', 'room-subject-teaching--community--pe-health-t3'),
  ('room-subject-teaching--community--pe-health', '家庭の価値観や宗教的背景との摩擦も生じます。', 'room-subject-teaching--community--pe-health-t3'),
  ('room-subject-teaching--community--pe-health', '保護者との事前の丁寧な説明と合意が不可欠だと思います。', 'room-subject-teaching--community--pe-health-t3'),
  ('room-subject-teaching--community--music-art', '効率や数値で表せないものを軽んじる風潮の表れだと感じます。', 'room-subject-teaching--community--music-art-t3'),
  ('room-subject-teaching--community--music-art', '感性や表現力は子どもの人生を豊かにする根幹。削減に反対するなら他の何を減らすのかを語らないと議論が進まないのが辛いが、部活動や地域の文化活動と連携させれば限られた時数を補うこともできると思います。', 'room-subject-teaching--community--music-art-t3'),
  ('room-subject-teaching--community--home-economics-technology', 'ものづくりとプログラミングは本来相性がいい。センサーやロボットを動かす中で、技術とプログラミングが自然につながる。ただ指導できる教員と設備の差が学力差にならないよう、体制整備とセットで進めたいです。', 'room-subject-teaching--community--home-economics-technology-t3'),
  ('room-subject-teaching--community--integrated-inquiry-time', '『調べてまとめる』だけならもうAIが代行できる時代。身につけるべきは『どんな問いを立てるか』と『得た答えをどう吟味するか』。成果物の完成度ではなく、思考の跡や試行錯誤のプロセスを評価する視点への転換が必要です。', 'room-subject-teaching--community--integrated-inquiry-time-t3'),
  ('room-subject-teaching--community--information-subject', '入試科目化された『情報』は、データを読み解き活用する力としてすべての分野で生きる。大学での学びや仕事に直結するため自然な流れだが、暗記中心にならずプログラミング的思考を評価する良問作りが生命線だと思います。', 'room-subject-teaching--community--information-subject-t3'),
  ('room-subject-teaching--community--information-subject', '指導できる教員と設備の差が懸念です。', 'room-subject-teaching--community--information-subject-t3'),
  ('room-subject-teaching--community--information-subject', '受験負担がまた増えるのかと不安になります。', 'room-subject-teaching--community--information-subject-t3'),
  ('room-subject-teaching--community--career-guidance', '特定の職業をゴールにするより『学び続ける力』や『変化に適応する力』を基軸にしたい。AIやデータで適性や選択肢を可視化するのは有効だが、最後に『どう生きたいか』を考えるのは本人。その主体性を育てる支援が大事です。', 'room-subject-teaching--community--career-guidance-t3'),
  ('room-subject-teaching--community--career-guidance', '生徒や保護者は具体的な職業像を知りたがります。', 'room-subject-teaching--community--career-guidance-t3'),
  ('room-subject-teaching--community--career-guidance', '偏差値より『夢中になれること』を軸にしたいです。', 'room-subject-teaching--community--career-guidance-t3')
) AS m(room_id, body, topic_id)
WHERE p.room_id = m.room_id
  AND p.body = m.body
  AND p.author_id IS NULL
  AND (p.topic_id IS NULL OR p.topic_id <> m.topic_id);
